### PR TITLE
Adding ability in API and CLI to filter executions based on the trigger instance id

### PR DESCRIPTION
**Pull request by skarmark**
This will let users track the sequence of what happened after a particular trigger was dispatched.

### CODE REVIEW

**Comment by Kami** [comment]
Thanks.

The CLI change looks good, but I believe we also need to update API controller (st2api/st2api/controllers/v1/executionsviews.py) to also support filtering on trigger instance id.

With regarding to the test failure (https://travis-ci.org/StackStorm/st2/jobs/65717211#L985) it seems to be the same issue as described here -https://github.com/StackStorm/st2/pull/1572#issuecomment-109541195 (/cc @m4dcoder).

**Comment by skarmark** [comment]
Kami, above commit does contain change to st2api/st2api/controllers/v1/executionsviews.py as well. Did you check that? I was able to run the api and provide the trigger instance id as one of the filters when testing.

**Comment by Kami** [comment]
@skarmark Ah, sorry, it looks like I missed that line :)

**Comment by Kami** [comment]
I've made minor tests change (previously we weren't correctly testing filters) and merged change into trunk. Thanks.

Since it's a minor change, I will also cherry-pick it on top of v0.11.1.

**Comment by skarmark** [comment]
Great. Thanks!

**Pull request merged**
