### PR TITLE
[no-merge] Adding stanley user and st2packs group

### PR DESCRIPTION
**Pull request by DoriftoShoes**

### CODE REVIEW

**Comment by manasdk** [comment]
merge?

**Comment by DoriftoShoes** [comment]
I thought we were going to wait on this stuff...Now I am confused.

**Comment by manasdk** [comment]
> I thought we were going to wait on this stuff...Now I am confused.
Ok. NO merge. I missed some conversation - all good!

**Comment by lakshmi-kannan** [comment]
Closing. Reopen if you need it.

**Pull request closed without merging**
