### PR TITLE
Sensor Logging Fixes

### PR DESCRIPTION
**Pull request by andrew-regan**
__Updates__
* Make sure the `getLogger()` call does not append more then one `st2.` prefix to the logger name to preserve the logging name hierarchy. This code from `st2reactor/st2reactor/container/sensor_wrapper.py` was creating loggers prefixed with `st2.st2.` because `self._sensor_wrapper._logger.name` is already prefixed with `st2.` and the call to `getLogger` would prefix an additional `st2.`:
```
    def get_logger(self, name):
        """
        Retrieve an instance of a logger to be used by the sensor class.
        """
        logger_name = '%s.%s' % (self._sensor_wrapper._logger.name, name)
        logger = logging.getLogger(logger_name)
        logger.propagate = True

        return logger
```
* Include the pack name in the logger named used by sensors since `self._class_name` does not have to be unique across packs

The current default logging setup shares the `st2sensorcontainer.log` across multiple processes which isn't really suppored. Using these changes its possible to break out individual log files per sensor via the `logging.sensorcontainer.conf`. Example changes:

```
[loggers]
keys=root,vSphereEventSensor

...

[logger_vSphereEventSensor]
level=DEBUG
handlers=consoleHandler, vSphereEventSensorFileHandler, vSphereEventSensorAuditHandler
propagate=0
qualname=st2.SensorWrapper.vsphere.EventSensor

...

[handler_vSphereEventSensorFileHandler]
class=handlers.RotatingFileHandler
level=DEBUG
formatter=verboseConsoleFormatter
args=("logs/vsphere_event_sensor.log",)
```

### CODE REVIEW

**Comment by manasdk** [comment]
:+1:

**Comment by lakshmi-kannan** [comment]
I'd appreciate if you could check in a sample logging conf in the repo under conf/ directory. This way people have a working example. We also need some basic documentation in https://github.com/StackStorm/st2docs/blob/master/docs/source/sensors.rst. Also a CHANGELOG entry in https://github.com/StackStorm/st2/blob/master/CHANGELOG.rst.

**Comment by andrew-regan** [comment]
@lakshmi-kannan 

1. @manasdk delivered https://github.com/StackStorm/st2docs/issues/60 earlier which documents this info in Configuration --> Configure Logging. Is this sufficient? Or do you want something in the sensor docs that points back to this?
2. Are the docs good enough to cover the sample? If not do you want the sample in `conf/` or `st2reactor/conf/`? What pack/sensor should the sample refer to?

Thanks,
Andrew

**Comment by lakshmi-kannan** [comment]
@andrew-regan: I am blind. I missed the docs changes. Looks good to me. I was wondering about the sample sensor in conf myself. Maybe when we ship something in core packs, I'll make this change.

**Comment by estee-tew** [comment]
https://stackstorm.slack.com/archives/stackstorm/p1455146832006656

**Comment by andrew-regan** [comment]
Sounds good. CHANGELOG.rst updated.

**Comment by andrew-regan** [comment]
Don't believe anything else is needed for this at the moment. Can't access the Slack link above from @estee-tew

**Comment by Kami** [comment]
Thanks! :+1:

**Pull request merged**
