### PR TITLE
Add `pack create` generators

### PR DESCRIPTION
**Pull request by enykeev**
[asciicast](https://asciinema.org/a/47pv75tjdoa132oi5ew2oc9yo)

### CODE REVIEW

**Comment by Kami** [comment]
Just a heads up - some of that functionality used to be part of st2sdk - https://github.com/stackstorm/st2sdk

We need to decide on how to proceed with st2sdk.

**Comment by enykeev** [comment]
@Kami we should probably just move it there completely. I somehow entirely missed the fact that we even have st2sdk.

**Comment by enykeev** [comment]
Oh, ok, so apparently st2sdk implementation is quite minimalistic so the question what to do is still open.

As for this PR, there's quite a few things I personally don't like in it and I'm hesitant to even try to fit it in this release.

For one, although cookiecutter takes some pain away, it's extremely limited and we're already using it pretty much to its limits.

I also don't like that you need to have a bunch of separate repos for templates. It's hard for me to estimate how often we would like to change this templates and that's an important part of consideration how we want to ship them.

Moreover, I personally never use content generators as they, in my experience, do more harm than good.

For one proposing the PR, I surely do have a lot of negative about it.

Moving it to a separate repo\tool might be actually a good idea. It would allow us to release it outside of st2 schedule, the moment we would actually think it's ready. We may also investigate possibility of connecting it to `st2client` in a more dynamic matter which would allow us to iterate on templates easily and more frequently.

**Comment by emedvedev** [comment]
> Moving it to a separate repo\tool might be actually a good idea

I think that would be the most sensible approach. I like the pack template generator, and I would probably use it (like, say, I'd use a boilerplate for a small React page rather than set everything up myself), but on my local machine. Creating a pack template on a StackStorm server only makes sense when there's a good way to sync, edit and share that pack (in our case, that would be a git repo).

**Comment by enykeev** [comment]
> I like the pack template generator, and I would probably use it, but on my local machine.

The idea was that you'll start using st2client on your machine too. You surely would not want to have them both required to write a pack, would you?

**Comment by emedvedev** [comment]
> The idea was that you'll start using st2client on your machine too. You surely would not want to have them both required to write a pack, would you?

Yeah, but if there's no easy way to push this pack to a server and synchronize, then cookiecutter is still nice, but kinda goes into the "bells and whistles" category.

**Comment by nmaludy** [comment]
+1

**Comment by lakshmi-kannan** [comment]
Closing. If you are working on this actively, please reopen @enykeev

**Pull request closed without merging**
