### PR TITLE
Fix bugs with newlines and unicode in execution formatter

### PR DESCRIPTION
**Pull request by Mierdin**
The execution formatter had some bugs that caused some problems with properly representing newline characters. This PR addresses two problems:

- Extra escape characters are added to the output of `yaml.safe_dump`. This means that newline characters `\n` are escaped, and are, as a result, not honored in the final client output. This means that complicated output like stack traces are output as a single line, which makes it wholly unreadable.
- `yaml.safe_dump` also adds a second `\n` to existing instances of `\n`, resulting in `\n\n`. Since we're printing this resulting value, this results in a lot of whitespace in output

# Explanation of Changes

As documented in #3855, the client has exhibited some strange behavior showing certain executions - in particular, Python stack traces:

```
~$ st2 run testpack.newline_test_error outcome="exception"
.
id: 5a1359b132ed3504e7a69b4f
status: failed
parameters:
  outcome: exception
result:
  exit_code: 1
  result: None
  stderr: "FOOBAR1\nTraceback (most recent call last):\n  File \"/home/vagrant/st2/st2common/st2common/runners/python_action_wrapper.py\", line 276, in <module>\n    obj.run()\n  File \"/home/vagrant/st2/st2common/st2common/runners/python_action_wrapper.py\", line 169, in run\n    output = action.run(**self._parameters)\n  File \"/opt/stackstorm/packs/testpack/actions/newline_test_error.py\", line 24, in run\n    raise Exception(\"This is an exception\")\nException: This is an exception\n"
  stdout: 'FOOBAR2

    '
```

The above example shows the entire stack trace on a single line, since the newline characters are escaped behind the scenes. This makes reading this stack trace incredibly hard to read. This is actually a VERY simple example - I've run into way worse examples during support for our own CI, such as when this comes up for tabular output, making tables 100% unreadable.

Please see [this comment](https://github.com/StackStorm/st2/issues/3855#issuecomment-345835804) for a detailed explanation of why this is happening.

The fix was to pass the resulting value for each attribute through `strutils.unescape()` once more. This stripped away the extra escape slashes, and newline characters are now rendered properly on output:

```
~$ st2 run testpack.newline_test_error outcome="exception"
.
id: 5a13599b32ed3504e7a69b4c
status: failed
parameters:
  outcome: exception
result:
  exit_code: 1
  result: None
  stderr: "FOOBAR1
Traceback (most recent call last):
  File "/home/vagrant/st2/st2common/st2common/runners/python_action_wrapper.py", line 276, in <module>
    obj.run()
  File "/home/vagrant/st2/st2common/st2common/runners/python_action_wrapper.py", line 169, in run
    output = action.run(**self._parameters)
  File "/opt/stackstorm/packs/testpack/actions/newline_test_error.py", line 24, in run
    raise Exception("This is an exception")
Exception: This is an exception
"
  stdout: 'FOOBAR2
    '
```

In addition, I added a new function for removing duplicate newlines introduced by `yaml.safe_dump`. This addresses the concerns brought up in #3602 - note that in the first output above, `stdout` contained a line of whitespace at the end, and in the second output, this whitespace is gone.

Closes https://github.com/StackStorm/st2/issues/3855
Closes https://github.com/StackStorm/st2/issues/3602

### CODE REVIEW

**Comment by Mierdin** [comment]
I added a test to address the unescape bug. Ensured it failed on `master` and resulted in a success in this branch - just making sure this regression is prevented in the future:

```
(virtualenv) vagrant@st2dev:~/st2$ nosetests -v st2client/tests/unit/test_formatters.py:TestExecutionResultFormatter.test_execution_unescape_newline
test_execution_unescape_newline (tests.unit.test_formatters.TestExecutionResultFormatter) ... FAIL

======================================================================
FAIL: test_execution_unescape_newline (tests.unit.test_formatters.TestExecutionResultFormatter)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vagrant/st2/virtualenv/local/lib/python2.7/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/home/vagrant/st2/st2client/tests/unit/test_formatters.py", line 120, in test_execution_unescape_newline
    self.assertEqual(content, FIXTURES['results']['execution_unescape_newline.txt'])
AssertionError: 'id: [155 chars]BAR1\\nTraceback (most recent call last):\\n "[54 chars]ue\n' != 'id: [155 chars]BAR1\nTraceback (most recent call last):\n "\n[50 chars]ue\n'
  id: 547e19561e2e2417d3dde123
  status: succeeded (1s elapsed)
  parameters: None
  result:
    localhost:
      failed: false
      return_code: 0
-     stderr: "FOOBAR1\nTraceback (most recent call last):\n "
+     stderr: "FOOBAR1
+ Traceback (most recent call last):
+  "
      stdout: 'FOOBAR2
-
        '
      succeeded: true
```

**Comment by Mierdin** [comment]
I wanted to make sure this was also fixed for our internal purposes, where we run tests from the CLI's perspective by basically interacting with the `st2` client with `core.local`. In the cases where exceptions were thrown in a workflow executed this way, the output table was horrendous:

screenshot 2017-11-20 19 03 00

With this PR, the output is much more reasonable (though there's some kind of unicode thing going on there - this seems to be only specific to this corner case of executing st2 commands via core.local):

screenshot 2017-11-20 19 05 47

**Comment by Kami** [comment]
LGTM, but probably also not a bad idea to run this on our CI server for a while since it's a behavior change to make sure everything is in order.

And good change, Python tracebacks look much better now :+1:

**Comment by nmaludy** [comment]
@Mierdin just an FYI those are ANSI escape sequences for colors in the terminal https://en.wikipedia.org/wiki/ANSI_escape_code

**Comment by Mierdin** [comment]
I reviewed the changes in https://github.com/StackStorm/st2/pull/3511, and after some discussion I thought it was useful to re-introduce the unicode encoding statement at the end of this formatting function. So that's done in https://github.com/StackStorm/st2/pull/3872/commits/8170226b3f02ce888b6462439751aaf90370c9d0

**Comment by Mierdin** [comment]
I put together a simple test to show where things are at as of now. Here's the output for a workflow that runs my test action:

```
---
  version: '2.0'
  testpack.wftest:
    type: direct
    tasks:
      my_task:
        action: core.local
        input:
          cmd: 'source /home/vagrant/st2/virtualenv/bin/activate && st2 run testpack.newline_test_error outcome="exception"'
```

output:

screenshot 2017-11-27 10 02 42

**Comment by Kami** [comment]
LGTM :+1: 

Let's merge it, deploy it to CI and see how it behaves there :)

**Pull request merged**
