### PR TITLE
Return empty list when pack not found in index

### PR DESCRIPTION
**Pull request by Mierdin**
Fixes https://github.com/StackStorm/st2/issues/3377

### CODE REVIEW

**Comment by Kami** [comment]
LGTM - the API result is indeed more consistent this way.

Please just document it in changelog and if you feel the need also upgrade notes entry since it's in theory a breaking change, yet a very small and non-significant one.

**Comment by armab** [comment]
@Mierdin Also please re-run the failed test to make sure we're all green.

**Comment by Mierdin** [comment]
@armab Re-ran the u16 execution and it succeeded - not sure why Github isn't showing the full 8 checks though.

**Comment by armab** [comment]
@Mierdin Thanks! Seems it's green now :+1:

**Pull request merged**
