### PR TITLE
Fix st2 apikey generation when auth is disabled

### PR DESCRIPTION
**Pull request by humblearner**
Addresses: #3578

### CODE REVIEW

**Comment by enykeev** [comment]
Nice find! There's a good chance I've used this pattern in other parts of the code base, so we need to be on a lookout. And to save @Kami some breath, tests are very welcome =)

**Comment by humblearner** [comment]
Yup, tests are on the way even codecov/patch is not happy. :) (_although not sure if it is ever happy_)

**Comment by armab** [comment]
Would be nice to have the respective changelog entry next time ;)

**Comment by humblearner** [comment]
Whoops, here you go: https://github.com/StackStorm/st2/pull/3599 . Thanks! 🙂

**Pull request merged**
