### PR TITLE
Fix master builds

### PR DESCRIPTION
**Pull request by cognifloyd**
Fixes includes:

Update gitpython requirement (Thanks to @blag for tracking down the bug.)

- gitpython requires gitdb2, but that has removed some things in newer
  versions, and 2.11.1 had an open ended dep. So, update gitpython to a
  newer version that has more specific version requirements for gitdb2.
- This should fix these errors:
  https://github.com/gitpython-developers/GitPython/issues/983
  https://travis-ci.org/StackStorm/st2/jobs/652088774#L9416
  https://circleci.com/gh/StackStorm-Exchange/stackstorm-sumologic/155

Drop --no-site-packages from virtualenv calls

Make travis use the travis user instead of stanley, and add a restricted permissions workaround for the root user.

Update requests which had a conflicting dep on idna (primary said `idna>=2.5,<2.9` but security extra wanted any `idna>=2.0.0`. idna 2.9 was released a couple of days ago, and requests 2.23.0 with fixed deps was released today.

### CODE REVIEW

**Comment by cognifloyd** [comment]
This won't fix all of the build errors on master. There are other issues as well, this is just the only one with a clear fix so far.

**Comment by cognifloyd** [comment]
Other issues include:
- something installing wrong idna version (`.st2client-install-check` in the Lint Checks build; can't find what changed here)
- build pack virtualenv fails (in 2.7 Integation Tests build. Maybe due to permissions issue? Build has no details)

Once we figure those issues out, they should probably go in separate PRs. Can we merge this fix even without resolving those other issues?

**Comment by m4dcoder** [comment]
@cognifloyd If these issues are causing the errors in the CI above, then you have to fix them before we can merge.

**Comment by blag** [comment]
NAK - investigating, will edit this comment in a bit

**Comment by cognifloyd** [comment]
I just cherry-picked the `--no-site-packages` fix from #4863. 
Plus I'm trying to resolve the permissions issue in a nicer way than the xenial workaround to see if that fixes the 2.7 integration tests.
Still stumped on the idna issue.

**Comment by cognifloyd** [comment]
It's GREEN! :green_heart:

**Comment by armab** [comment]
It's arguable pip requirements fix needs _that_ amount of changes. I'd prefer to not mix different changes in one PR. This keeps history clear and straightforward.

Additionally, per previous comment we're missing CHANGELOG record which is required for pip requirements update for st2 core.

Even though, many thanks for fixing master! :heavy_check_mark:

**Comment by cognifloyd** [comment]
@blag asked me to get rid of the 777 permissions workaround affecting the entire home directory.
I'm not sure why precise started having permissions issues, but I needed to adjust something, so I moved some of the permissions changes from #4863 to this PR to resolve that, only I made sure to do something that would selectively change permissions only where needed.

So, no, this was not just a pip dep update.

Changelog PR coming soon.

**Pull request merged**
