### PR TITLE
st2 packaging: release fix in version string

### PR DESCRIPTION
**Pull request by dennybaa**
minor fix of the release of debian packages

### CODE REVIEW

**Comment by Kami** [comment]
Just curious, will this counter (ST2PKG_RELEASE) get auto incremented on each release or how is this supposed to work?

**Comment by Kami** [comment]
In any case, LGTM & merged. Thanks.

**Comment by dennybaa** [comment]
np! noop, it's not a counter. It should be implemented externally, this is just an input variable. So if there's a proper number somewhere it can be passed as this env var.

**Comment by Kami** [comment]
Ah, thought it might be something like that.

Thanks for the clarification.

**Pull request merged**
