### PR TITLE
[RBAC] Only allow limit=-1 to be used by admins, allow admins to override max_page_size

### PR DESCRIPTION
**Pull request by Kami**
This pull request adds some RBAC changes on top off #3761 we have agreed upon.

1. Only allow `limit=-1` (aka retrieve all the results at once) be used by RBAC admins
2. Allow RBAC admins to specify arbitrary large value for `?limit` parameter even if it's larger than `max_page_size` config option (in short, `max_page_size` limit only applies to non-admin users)

### CODE REVIEW

**Comment by armab** [comment]
I just tried packages.
Not related to @Kami's PR, but `st2 action list` is missing `--limit` param in CLI, as well as some other actions cc @humblearner

**Comment by Kami** [comment]
> Also just to double check: -1 should work for default non-enterprise StackStorm installation.

Yes, RBAC is disabled in default installation so it should work out of the box.

**Comment by Kami** [comment]
@armab Good catch.

I'm going over test case to make sure we have "get all" test case for all the RBAC enabled API endpoints.

**Comment by Kami** [comment]
@armab Pushed fixes and test cases, please see last couple of commits.

**Comment by Kami** [comment]
Yeah, not all API endpoint support pagination right now (including `?sort` and `?offset` query parameter) and it would be to fix that and make it consistent across the board.

**Comment by armab** [comment]
Just for reference, list of missing CLI: https://github.com/StackStorm/st2/issues/3940 as another issue.

**Pull request merged**
