### PR TITLE
Add a --use-python3 flag to st2-pack-install CLI tool

### PR DESCRIPTION
**Pull request by dswebbthg**
…k-install to specify whether to use python3 for the setup of the virtualenv during a pack install

### CODE REVIEW

**Comment by Kami** [comment]
LGTM, thanks :+1: 

(On a related note - this feature will be deprecated in the not so distant future once we announce official support for StackStorm running under Python 3 - https://stackstorm.com/2018/12/14/pre-change-freeze-stackstorm-2-10/)

**Comment by dswebbthg** [comment]
> LGTM, thanks +1
> 
> (On a related note - this feature will be deprecated in the not so distant future once we announce official support for StackStorm running under Python 3 - https://stackstorm.com/2018/12/14/pre-change-freeze-stackstorm-2-10/)

perfect, was running into the python3 issues running the stackstorm-ha setup so looking forward to the docker images getting bumped to 18.04 and python 3.6.

**Comment by Kami** [comment]
@dswebbthg In the mean time, if you feel adventurous, you can test the new v2.10dev / v3.0dev Ubuntu Bionic packages which use Python 3.

We are running all integration and end to end tests under Python 3 already, but we shipped beta early so we also get more real-life testing from our users.

**Comment by Kami** [comment]
Great, keep us posted :)

**Comment by dswebbthg** [comment]
created a pull request over at the st2-dockerfiles repo with what I've found so far, will add any additional commits as testing progresses.  So far just a few small tweaks needed.

**Comment by Kami** [comment]
Merged, thanks!

**Pull request merged**
