### PR TITLE
Update service.py

### LINKED ISSUE #3842: Action 'linux.service' fails on Centos7
When I tried to execute restart some service on the Centos7 server got the following error:
```
Traceback (most recent call last):
  File "/tmp/5a0459bc07ac686fb813a920/service.py", line 24, in <module>
    subprocess.call(cmd, shell=True)
NameError: name 'cmd' is not defined
```
After investigation the resolution has been found:
in file /opt/stackstorm/packs/linux/actions/service.py the entry

`elif re.search(distro, 'Redhat') or re.search(distro, 'Fedora'):`

fixed to 

`elif re.search(distro, 'Redhat') or re.search(distro, 'Fedora') or re.search(distro, 'CentOS Linux'):`

The issue has gone

### PR DESCRIPTION
**Pull request by shkadov**
for fix issue linux.service on the Centos7

Fixes #3842

### CODE REVIEW

**Comment by Kami** [comment]
Can you please fix lint issue - https://travis-ci.org/StackStorm/st2/jobs/299652725?

Besides that - LGTM and thank you for your contribution :+1:

**Comment by armab** [comment]
@shkadov Please also include a changelog entry for this fix, see:
https://github.com/StackStorm/st2/blob/master/CHANGELOG.rst to follow the format.

**Comment by shkadov** [comment]
@Kami Done
@armab Included

**Comment by Kami** [comment]
@shkadov I believe you forgot to add / commit changelog entry change.

**Comment by shkadov** [comment]
@Kami 
Done

**Comment by LindsayHill** [comment]
One more minor thing (sorry to be a pain) - can you bump the version number here https://github.com/StackStorm/st2/blob/master/contrib/linux/pack.yaml from 1.0.0 to 1.0.1?

**Comment by Kami** [comment]
I will go ahead and merge those PRs - thanks!

In the future, it would be a bit easier for us if you keep related changes such as those part of a single PR :)

**Pull request merged**
