### PR TITLE
Fix typo in the supported API filters when filtering packs

### PR DESCRIPTION
**Pull request by winem**
This PR fixes the issue I found tonight when testing the tag filter as reported in #4918 and adds unit tests to test the API with actions filtered by the name or tag.

### CODE REVIEW

**Comment by winem** [comment]
Please don't merge it yet, I'm currently fixing the new unit tests to avoid that this feature breaks unnoticed again. Will drop another comment and remove the `WIP:` once the unit tests were successful.

**Comment by armab** [comment]
:+1:  We definitely want to include this for `v3.2`.
@winem Just converted this PR to draft to make sure we don't merge it before you're ready.

See https://github.blog/2019-02-14-introducing-draft-pull-requests/

**Comment by winem** [comment]
@armab thanks for the support. I think and hope that especially the unit tests will be useful in the future.

The tests run fine when I run them locally with nosetests and I can not really see the root cause for the failing travis tests in the code itself. It looks more like a infrastructure issue or an issue with external dependencies (services, dbs, ...). 

I'll remove the WIP flag now and would like to ask for a 2nd opinion regarding the failing tests.

**Comment by armab** [comment]
@winem I just re-started CI jobs and they're green now.
Probably was a temporary failure from TravisCI.

**Pull request merged**
