### PR TITLE
Moved download server to variable and pointed to downloads server

### PR DESCRIPTION
**Pull request by DoriftoShoes**
This PR creates a variable for the downloads server and sets it to the new public downloads server.

### CODE REVIEW

**Comment by Kami** [comment]
There appears to be some differences between this new server and https://ops.stackstorm.net/releases/st2/.

* https://downloads.stackstorm.net/releases/st2/0.8.3/ - misses st2_deploy.sh file.
* https://downloads.stackstorm.net/releases/st2/0.8.9dev/ - misses st2_deploy.sh file
* https://downloads.stackstorm.net/releases/st2/ - no 0.8dev directory
* ...

**Comment by DoriftoShoes** [comment]
The new wrapper looks in the {TYPE} subdirectory for the st2_deploy.sh file.  I did not copy over the 0.8dev packages since people should be pulling either 0.8.X or 0.9dev.  If we feel the 0.8dev packages are necessary I can put them there.  Do we want to leave 0.8dev out there?

**Comment by Kami** [comment]
I'm fine with not including 0.8dev - just wanted to make sure it was a conscious decision :)

**Comment by DoriftoShoes** [comment]
Yup :) I did it on purpose.  Also the st2_deploy.sh location doesn't matter since it is hardcoded in to the new wrapper script that is pulled from the scripts/ directory.

**Comment by DoriftoShoes** [comment]
For consistency's sake I copied the appropriate st2_deploy.sh scripts into the root of the version dir.

**Pull request merged**
