### PR TITLE
Fixate reqs update

### PR DESCRIPTION
**Pull request by dennybaa**
st2 debug builds with latest pecan. But expect it should use ours.

### CODE REVIEW

**Comment by Kami** [comment]
As noted on slack - only st2api and st2debug depend on pecan.

st2debug contains a standalone CLI utility which doesn't depend and need pecan.

**Comment by dennybaa** [comment]
ok. sure I removed st2debug pecan addition. It's not here'
Just merge the makefiles. I've cleand up this PR. Thank you.

**Comment by Kami** [comment]
Merged, thanks.

**Comment by dennybaa** [comment]
gracias!

**Pull request merged**
