### PR TITLE
s/results_tracker/resultstracker in config

### PR DESCRIPTION
**Pull request by lakshmi-kannan**
Fixes: https://github.com/StackStorm/st2/issues/3500

Context: 

There was already a ``resultstracker`` config group but I accidentally shipped the new configs in ``results_tracker`` config section. With this PR, I am adding a deprecation warning for ``results_tracker`` section but we will still parse it. Going forward, 

The config will stay 

```
[resultstracker]
query_interval = 0.1
```

Since we introduced ``results_tracker`` as a config group, we'll support it for this version and then deprecate the config. So we'll pick up 

```
[results_tracker]
query_interval = 0.1
```

This will however spit out a warning to remind people.

### CODE REVIEW

**Comment by lakshmi-kannan** [comment]
Will update CHANGELOG before merge to master.

**Comment by m4dcoder** [comment]
Btw, does it make sense to move the configs at https://github.com/StackStorm/st2/blob/v2.2/st2actions/st2actions/resultstracker/config.py to the same location as the configs here?

**Comment by lakshmi-kannan** [comment]
>Btw, does it make sense to move the configs at https://github.com/StackStorm/st2/blob/v2.2/st2actions/st2actions/resultstracker/config.py to the same location as the configs here?

I thought about it but the jitter_interval etc are specific to mistral runner and they are in st2common. So from a programmer perspective, it made sense to lump them all in st2common.

**Comment by Kami** [comment]
We still have some inconsistencies like `system_user`, etc.

Down the road, I would prefer to make it consistent and just use `_` everywhere.

**Pull request merged**
