### PR TITLE
Package purge_* tools

### PR DESCRIPTION
**Pull request by manasdk**

### CODE REVIEW

**Comment by lakshmi-kannan** [comment]
All tools follow st2-* convention. So st2-purge-executions would be better IMO.

**Comment by Kami** [comment]
@lakshmi-kannan +1

**Comment by lakshmi-kannan** [comment]
Also, if we decide to change the name, let's update https://github.com/StackStorm/st2/blob/master/docs/source/troubleshooting/purging_old_data.rst

**Comment by manasdk** [comment]
@lakshmi-kannan You wish is my command efb208365fc01d1ebf91511009791a9678d51ea8

**Comment by lakshmi-kannan** [comment]
lgtm

**Pull request merged**
