### PR TITLE
Set loglevel for nosetests to INFO

### PR DESCRIPTION
**Pull request by enykeev**

### CODE REVIEW

**Comment by enykeev** [comment]
I don't like the fact that we have to add `setup.cfg` to the repo root either, but that's how `nosetests` work, it only looks for `./setup.cfg`, `~/.noserc` or `~/nose.conf` by default.

**Comment by Kami** [comment]
Will check it out locally.

**Comment by Kami** [comment]
Yeah, much better, thanks.

Can you please also update developer documentation (testing section) and clarify how to set log level to debug if needed (e.g. `nosetests --logging-level DEBUG` ...)?

**Comment by Kami** [comment]
> I don't like the fact that we have to add setup.cfg to the repo root either, but that's how nosetests work, it only looks for ./setup.cfg, ~/.noserc or ~/nose.conf by default.

Can't we use ``--logging-level`` CLI argument?

**Comment by enykeev** [comment]
We can, but you'll also have to do that for every manual call of nosetests which may prove annoying. Better to have sane default and go from there.

**Pull request merged**
