### PR TITLE
docs: fix simple typo, workound -> workaround

### PR DESCRIPTION
**Pull request by timgates42**
There is a small typo in st2api/tests/unit/controllers/v1/test_auth.py, st2api/tests/unit/controllers/v1/test_auth_api_keys.py.

Should read `workaround` rather than `workound`.

Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

### CODE REVIEW

**Review by cognifloyd — APPROVED** [review]
This shouldn't need passing tests as it only changes typos in comments. @StackStorm/tsc can we merge this please?

**Comment by amanda11** [comment]
> This shouldn't need passing tests as it only changes typos in comments. @StackStorm/tsc can we merge this please?

Needs updating with master branch before can be merged, and I think only senior maintainers can merge without tests passing...

Will trigger an update branch...

**Review by amanda11 — APPROVED** [review]
LGTM

**Comment by cognifloyd** [comment]
All tests pass as expected. Merge away :)

**Pull request merged**
