### PR TITLE
Proposing to add st2-self-check into this section

### PR DESCRIPTION
**Pull request by kirilstrax**

### CODE REVIEW

**Comment by Kami** [comment]
IIRC, self-check script won't work out of the box since it depends on `examples` and `tests` packs which are not installed by default anymore (on CI server we run setup-examples and setup-test scripts).

**Comment by Kami** [comment]
If that's indeed the case, we should consider adding a new section called "Extended Validation" or similar where we explain that the user first needs to set up test packs using setup-* scripts...

**Comment by st2stanley** [comment]
Self-check installs those packs if they aren't already there.

Pwh

**Comment by Kami** [comment]
@DoriftoShoes Thanks. I did actually check the self check script, but I missed that part, lol.

In this case, LGTM and ignore my comments :)

**Comment by dzimine** [comment]
-1: Good content but move this to "troubleshooting" section: we shall keep the 'green path' documentation short and right to the point.

**Comment by kirilstrax** [comment]
Based on @dzimine 's comment moved to troubleshooting, closing this pull request

**Pull request closed without merging**
