### PR TITLE
Revert dependency upgrades

### PR DESCRIPTION
**Pull request by Kami**
Let's see if this helps with #3596 and #3595.

_Update:_
Fixes https://github.com/StackStorm/st2/issues/3595

### CODE REVIEW

**Comment by Kami** [comment]
@armab 

I managed to track down the memory usage issue to mongonegine 0.13.0. Upgrading to 0.13.0 doubles the memory usage, it's easy to replicate it (install latest dev packages, revert mongoengine to 0.11.0 or 0.12.0 and restart services, wait a bit for them to start up and check memory usage).

I will also go ahead and revert mongoengine upgrade for now and try to track down the actual place in mongoengine where it happens.

Great catch and thanks again.

**Comment by armab** [comment]
```
$ st2 --version
Traceback (most recent call last):
  File "/usr/bin/st2", line 7, in <module>
    from st2client.shell import main
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2client/shell.py", line 34, in <module>
    from st2client.base import BaseCLIApp
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2client/base.py", line 26, in <module>
    import urllib3
ImportError: No module named urllib3
```

**Comment by armab** [comment]
@Kami Taking into account `ImportError: No module named urllib3`, this part from the pip upgrade should be reverted as well: https://github.com/StackStorm/st2/pull/3538/files#r128815747 So the package failure is valid.

I can confirm `mongo` memory fix. 
Please also test if reverting requests fixes https://github.com/StackStorm/st2/issues/3596 under `EL7`.

**Comment by Kami** [comment]
@armab Thanks for confirming and will do.

**Pull request merged**
