### PR TITLE
(RBAC enable) Fix when permission_type is not provided with API call

### PR DESCRIPTION
**Pull request by humblearner**
Fix for #3348

### CODE REVIEW

**Comment by enykeev** [comment]
It seems to me that instead of fixing the problem, it masks it. The problem is that we forget to provide a permission_type for some endpoints. Essentially, `permission_type` method argument should be mandatory. Removing RBAC check from code path creates a security regression.

**Comment by humblearner** [comment]
Couldn't find permission_type for Triggers: https://github.com/StackStorm/st2/blob/master/st2common/st2common/rbac/types.py

Are we using some other type for triggers ?

**Comment by enykeev** [comment]
Yep, I've just stumble on that myself. We indeed don't have RBAC definitions for triggers, rbac roles and pack config schemas - the only three endpoints that use that method. I still think that we should  make `permission_type` argument mandatory and manually set it to None in this three cases to ensure we don't accidentally leak something we do have rbac definition for. I'll add it to this PR.

**Comment by Kami** [comment]
Yeah, I agree with last comment - I think explicitly passing in `None` for endpoints where we don't have RBAC (yet) is better.

We also need tests for this - I can work on it later today.

**Pull request merged**
