### PR TITLE
Addding ability to set stream URL for st2client.

### LINKED ISSUE #3431: ST2 Client Stream URL
ST2 Client does not have the option to configure the stream URL which breaks some commands (I.E. `st2 pack install`) when using ST2 Client remotely. ST2 Client should allow for configurable stream URL so that commands that subscribe to the stream can update properly and not throw a traceback.

### PR DESCRIPTION
**Pull request by bigmstone**
- [x] Tests

Fixes #3431

### CODE REVIEW

**Comment by Kami** [comment]
So far, LGTM.

**Comment by cognifloyd** [comment]
I just tested this by modifying my pip --user installed copy of st2client against a fresh instance of st2 (in docker). Now, I get an ssl error message, probably due to the self-signed cert in the docker container. However, unlike the other APIs, where this results in an ssl warning, using the stream API results in an ERROR.
```
~ $ st2 pack list                                                                                    1
/home/cognifloyd/.local/lib64/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:838: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/security.html
  InsecureRequestWarning)
+-----------+-----------+-----------------------+---------+------------------+
| ref       | name      | description           | version | author           |
+-----------+-----------+-----------------------+---------+------------------+
| bitbucket | bitbucket | Pack which allows     | 0.3.0   | Aamir            |
|           |           | integration with      |         |                  |
|           |           | Bitbucket.            |         |                  |
| chatops   | chatops   | Chatops integration   | 0.2.0   | Kirill Enykeev   |
|           |           | pack                  |         |                  |
| core      | core      | st2 content pack      | 0.2.1   | st2-dev          |
|           |           | containing basic      |         |                  |
|           |           | actions.              |         |                  |
| default   | default   | Pack where all the    | 0.1.0   | st2-dev          |
|           |           | resources which are   |         |                  |
|           |           | created using the API |         |                  |
|           |           | and don't have a pack |         |                  |
|           |           | specified get saved.  |         |                  |
| github    | github    | st2 content pack      | 0.6.2   | StackStorm, Inc. |
|           |           | containing github     |         |                  |
|           |           | integrations          |         |                  |
| linux     | linux     | Generic linux actions | 0.1.0   | st2-dev          |
| packs     | packs     | core st2 content pack | 0.2.0   | st2-dev          |
|           |           | containing pack       |         |                  |
|           |           | management            |         |                  |
|           |           | functionality.        |         |                  |
| slack     | slack     | st2 content pack      | 0.3.0   | StackStorm, Inc. |
|           |           | containing slack      |         |                  |
|           |           | integrations          |         |                  |
+-----------+-----------+-----------------------+---------+------------------+
 ~ $ st2 pack install git                                                                                 1
/home/cognifloyd/.local/lib64/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:838: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/security.html
  InsecureRequestWarning)
ERROR: ("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",)

 ✘ ~ $
```

The execution completes, just as it did before, but I still can't see the streamed status messages. Perhaps another setting is needed to disable the ssl verification? In any case, why does the stream API result in an ERROR while the other APIs merely show the ssl warning?

**Comment by Kami** [comment]
What's our plan for this and what else needs to be done here?

Do we plan to get it finished and included in time for v2.3.2?

**Comment by Kami** [comment]
LGTM :+1: 

But we will also need to test it when rolling out v2.3.2 packages to make sure everything is in order there as well.

**Comment by Kami** [comment]
Will go ahead merge it and cherry pick it into v2.3.2 release branch.

**Comment by armab** [comment]
:+1:

**Pull request merged**
