### PR TITLE
Updates for v3.4.1

### PR DESCRIPTION
**Pull request by blag**
This PR pulls the changes from #5182 into the `v3.4` branch.

### CODE REVIEW

**Comment by armab** [comment]
CI is failing with:
```
cat: /root/.ssh/st2_id_rsa.pub: No such file or directory
Error: Process completed with exit code 1.
```

I think it's something new that happened with the upstream GH Actions Docker images and build environment.
@m4dcoder did you experience the same in the Orquesta repo?

**Review by Kami — APPROVED** [review]
LGTM :+1: once the tests pass.

**Comment by Kami** [comment]
On a related note - did you have a chance yet to re-enable the disabled st2tests test and verify it's working now? :)

**Comment by blag** [comment]
Verified.

[Failed](https://st2cicd.uswest2.stackstorm.net/#/history/6049dac99f7b9e85f2bb7ae6):
3.4.0 stable production

[Passing](https://st2cicd.uswest2.stackstorm.net/#/history/6049d5639f7b9e85f2bb7ade):

**Comment by blag** [comment]
We may need to update our flake8 settings to make sure they don't conflict with black:

```python
    # Warn on non utf-8 locale which could cause issues when running under Python 3 and working
    # with unicode data
    if (
        fs_encoding.lower() not in VALID_UTF8_ENCODINGS
        or encoding.lower() not in VALID_UTF8_ENCODINGS
    ):
```

```bash
flake8 st2common/st2common/service_setup.py
# st2common/st2common/service_setup.py:163:9: W503 line break before binary operator
```

```python
    # Warn on non utf-8 locale which could cause issues when running under Python 3 and working
    # with unicode data
    if (
        fs_encoding.lower() not in VALID_UTF8_ENCODINGS or
        encoding.lower() not in VALID_UTF8_ENCODINGS
    ):
```

```bash
flake8 st2common/st2common/service_setup.py
# (okay)
black st2common/st2common/service_setup.py
# reformatted st2common/st2common/service_setup.py
# All done! ✨ 🍰 ✨
# 1 file reformatted.
flake8 st2common/st2common/service_setup.py
# st2common/st2common/service_setup.py:170:9: W503 line break before binary operator
```

**Review by Kami — APPROVED** [review]

**Review by winem — APPROVED** [review]

**Review by punkrokk — APPROVED** [review]

**Pull request merged**
