### PR TITLE
Stop gunicorn processes in st2stop()

### PR DESCRIPTION
**Pull request by andrew-regan**
__Updates__
* If *use_gunicorn* is True then kill the associated st2api and st2auth processes
* Fix typos

### CODE REVIEW

**Comment by lakshmi-kannan** [comment]
@andrew-regan Did you try to figure out why gunicorn processes won't stop?

**Comment by andrew-regan** [comment]
Sort of. The current implementation in st2stop() goes after PPID's. 

Example the following PPID's will be killed :
```
regana@reganas-mbp ~/Development/git/plexxi_st2> screen -ls | grep st2 | cut -d. -f1 | awk '{print $1}'
95166
95170
95173
95176
95179
95183
95187
```
Which leaves behind the gunicorn processes:
```
regana@reganas-mbp ~/Development/git/plexxi_st2> ps -el | grep "st2\|UID"
  UID   PID  PPID        F CPU PRI NI       SZ    RSS WCHAN     S             ADDR TTY           TIME CMD
  501 95166     1      104   0  31  0  2445376    644 -      Ss                  0 ??         0:00.04 SCREEN -d -m -S st2-api ./virtualenv/bin/gunicorn_pecan ./st2api/st2api/gunicorn_config.py -k eventlet -b 127.0.0.1:9101 --workers 1
  501 95170     1      104   0  31  0  2454592    636 -      Ss                  0 ??         0:00.00 SCREEN -d -m -S st2-actionrunner-1 ./virtualenv/bin/python ./st2actions/bin/st2actionrunner --config-file /Users/regana/Development/git/plexxi_st2/./tools/../conf/st2.dev.conf
  501 95173     1      104   0  31  0  2455616    656 -      Ss                  0 ??         0:00.01 SCREEN -d -m -S st2-sensorcontainer ./virtualenv/bin/python ./st2reactor/bin/st2sensorcontainer --config-file /Users/regana/Development/git/plexxi_st2/./tools/../conf/st2.dev.conf
  501 95176     1      104   0  31  0  2462784    668 -      Ss                  0 ??         0:00.01 SCREEN -d -m -S st2-rulesengine ./virtualenv/bin/python ./st2reactor/bin/st2rulesengine --config-file /Users/regana/Development/git/plexxi_st2/./tools/../conf/st2.dev.conf
  501 95179     1      104   0  31  0  2472000    668 -      Ss                  0 ??         0:00.00 SCREEN -d -m -S st2-resultstracker ./virtualenv/bin/python ./st2actions/bin/st2resultstracker --config-file /Users/regana/Development/git/plexxi_st2/./tools/../conf/st2.dev.conf
  501 95183     1      104   0  31  0  2472000    660 -      Ss                  0 ??         0:00.00 SCREEN -d -m -S st2-notifier ./virtualenv/bin/python ./st2actions/bin/st2notifier --config-file /Users/regana/Development/git/plexxi_st2/./tools/../conf/st2.dev.conf
  501 95187     1      104   0  31  0  2472000    656 -      Ss                  0 ??         0:00.00 SCREEN -d -m -S st2-auth ./virtualenv/bin/gunicorn_pecan ./st2auth/st2auth/gunicorn_config.py -k eventlet -b 127.0.0.1:9100 --workers 1
  501 95665 86159     4006   0  31  0  2436888    800 -      S+                  0 ttys006    0:00.00 grep st2\|UID
    0 95168 95166     4106   0  31  0  2516064   4288 -      Ss+                 0 ttys007    0:00.01 login -pflq regana ./virtualenv/bin/gunicorn_pecan ./st2api/st2api/gunicorn_config.py -k eventlet -b 127.0.0.1:9101 --workers 1
  501 95181 95168     4006   0  31  0  2525600  32392 -      S+                  0 ttys007    0:00.74 /Users/regana/Development/git/plexxi_st2/virtualenv/bin/python ./virtualenv/bin/gunicorn_pecan ./st2api/st2api/gunicorn_config.py -k eventlet -b 127.0.0.1:9101 --workers 1
  501 95226 95181      106   0  31  0  2543472  54908 -      S+                  0 ttys007    0:02.02 /Users/regana/Development/git/plexxi_st2/virtualenv/bin/python ./virtualenv/bin/gunicorn_pecan ./st2api/st2api/gunicorn_config.py -k eventlet -b 127.0.0.1:9101 --workers 1
    0 95172 95170     4106   0  31  0  2507872   4252 -      Ss+                 0 ttys008    0:00.01 login -pflq regana ./virtualenv/bin/python ./st2actions/bin/st2actionrunner --config-file /Users/regana/Development/git/plexxi_st2/./tools/../conf/st2.dev.conf
  501 95186 95172     4006   0  31  0  2542956  55852 -      S+                  0 ttys008    0:01.38 python ./st2actions/bin/st2actionrunner --config-file /Users/regana/Development/git/plexxi_st2/./tools/../conf/st2.dev.conf
    0 95175 95173     4106   0  31  0  2516064   4300 -      Ss+                 0 ttys009    0:00.02 login -pflq regana ./virtualenv/bin/python ./st2reactor/bin/st2sensorcontainer --config-file /Users/regana/Development/git/plexxi_st2/./tools/../conf/st2.dev.conf
  501 95191 95175     4006   0  31  0  2536732  46060 -      S+                  0 ttys009    0:01.15 python ./st2reactor/bin/st2sensorcontainer --config-file /Users/regana/Development/git/plexxi_st2/./tools/../conf/st2.dev.conf
  501 95234 95191     4006   0  31  0  2564952  58592 -      S+                  0 ttys009    0:04.42 /opt/stackstorm/virtualenvs/vsphere/bin/python /Users/regana/Development/git/plexxi_st2/st2reactor/st2reactor/container/sensor_wrapper.py --pack=vsphere --file-path=/opt/stackstorm/packs/vsphere/sensors/vsphere_event_sensor.py --class-name=EventSensor --trigger-type-refs=vsphere.event --parent-args=["--config-file", "/Users/regana/Development/git/plexxi_st2/./tools/../conf/st2.dev.conf"] --poll-interval=5
  501 95240 95191     4006   0  31  0  2541636  49632 -      S+                  0 ttys009    0:00.79 /opt/stackstorm/virtualenvs/scaleio/bin/python /Users/regana/Development/git/plexxi_st2/st2reactor/st2reactor/container/sensor_wrapper.py --pack=scaleio --file-path=/opt/stackstorm/packs/scaleio/sensors/status_sensor.py --class-name=StatusSensor --trigger-type-refs=scaleio.status_notification,scaleio.sensor_log --parent-args=["--config-file", "/Users/regana/Development/git/plexxi_st2/./tools/../conf/st2.dev.conf"] --poll-interval=10
    0 95178 95176     4106   0  31  0  2516064   4264 -      Ss+                 0 ttys010    0:00.02 login -pflq regana ./virtualenv/bin/python ./st2reactor/bin/st2rulesengine --config-file /Users/regana/Development/git/plexxi_st2/./tools/../conf/st2.dev.conf
  501 95193 95178     4006   0  31  0  2536240  48672 -      S+                  0 ttys010    0:03.49 python ./st2reactor/bin/st2rulesengine --config-file /Users/regana/Development/git/plexxi_st2/./tools/../conf/st2.dev.conf
    0 95182 95179     4106   0  31  0  2516064   4284 -      Ss+                 0 ttys011    0:00.02 login -pflq regana ./virtualenv/bin/python ./st2actions/bin/st2resultstracker --config-file /Users/regana/Development/git/plexxi_st2/./tools/../conf/st2.dev.conf
  501 95195 95182     4006   0  31  0  2536720  46384 -      S+                  0 ttys011    0:01.08 python ./st2actions/bin/st2resultstracker --config-file /Users/regana/Development/git/plexxi_st2/./tools/../conf/st2.dev.conf
    0 95185 95183     4106   0  31  0  2516064   4340 -      Ss+                 0 ttys012    0:00.02 login -pflq regana ./virtualenv/bin/python ./st2actions/bin/st2notifier --config-file /Users/regana/Development/git/plexxi_st2/./tools/../conf/st2.dev.conf
  501 95198 95185     4006   0  31  0  2538784  50188 -      S+                  0 ttys012    0:02.44 python ./st2actions/bin/st2notifier --config-file /Users/regana/Development/git/plexxi_st2/./tools/../conf/st2.dev.conf
    0 95189 95187     4106   0  31  0  2516064   4344 -      Ss+                 0 ttys016    0:00.02 login -pflq regana ./virtualenv/bin/gunicorn_pecan ./st2auth/st2auth/gunicorn_config.py -k eventlet -b 127.0.0.1:9100 --workers 1
  501 95201 95189     4006   0  31  0  2525600  32376 -      S+                  0 ttys016    0:00.69 /Users/regana/Development/git/plexxi_st2/virtualenv/bin/python ./virtualenv/bin/gunicorn_pecan ./st2auth/st2auth/gunicorn_config.py -k eventlet -b 127.0.0.1:9100 --workers 1
  501 95225 95201      106   0  31  0  2534348  43840 -      S+                  0 ttys016    0:00.46 /Users/regana/Development/git/plexxi_st2/virtualenv/bin/python ./virtualenv/bin/gunicorn_pecan ./st2auth/st2auth/gunicorn_config.py -k eventlet -b 127.0.0.1:9100 --workers 1
```

**Comment by lakshmi-kannan** [comment]
Ahh! Good catch. Thanks for the fix! Will merge when travis is happy.

**Comment by lakshmi-kannan** [comment]
Travis tests aren't running. We don't have tests for this bash script. So yolo merged it.

**Comment by Kami** [comment]
To clarify - so now we also kill child / worker processes (previously we only killed master / parent process)?

It's weird if the children't weren't killed when we killed the master / parent, but anyways, I'm fine with this change.

**Comment by andrew-regan** [comment]
The switch to gunicorn with the existing pkill logic was always leaving 4 child processes around. They would cause subsequent restarts to silently fail because port 9101 was still bound by the gunicorn process.

**Comment by manasdk** [comment]
Oddly the behavior on Linux was a lot more unpredictable. I usually see a cleanup of child processes but 1/10 times processes would remain. On OSX it seemed to consistently stick around.

**Pull request merged**
