### PR TITLE
Changes for v2.2.1 release

### PR DESCRIPTION
**Pull request by Kami**
This pull request includes additional changes we want in the v2.2.1 release:

* https://github.com/StackStorm/st2/pull/3242
* https://github.com/StackStorm/st2/pull/3285
* https://github.com/StackStorm/st2/pull/3275
* https://github.com/StackStorm/st2/pull/3268
* https://github.com/StackStorm/st2/pull/3265
* https://github.com/StackStorm/st2/pull/3281

Those changes were already supposed to be included in https://github.com/StackStorm/st2/pull/3287, but they weren't (probably because of a failed cherry-pick which I failed to notice).

This was originally caught and reported by @warrenvw  (great catch, thanks!).

### CODE REVIEW

**Comment by Kami** [comment]
@Mierdin once this is resolved and merged we will sadly need to re-spin the testing process with the latest v2.2.1 packages.

**Comment by Kami** [comment]
st2-packages build is failing because it's incorrectly using st2-packages master branch and not v2.2 :/

**Comment by Kami** [comment]
I believe it's the same issue as last time - will merge this PR and then it should correctly trigger a build and build packages using v2.2 branch of st2-packages repo.

**Comment by Mierdin** [comment]
@Kami This appears to only have the changes from https://github.com/StackStorm/st2/pull/3242 - only two files changed. Yet there are 36 commits listed here across 6 PRs - am I missing something?

**Comment by Kami** [comment]
@Mierdin Yeah, it seems like a weird Github bug.

Before the merge the diff correctly showed all the changes, but after I merged the PR it now only shows 2 changed files. I would imagine it's probably some bug with how Github handles merged with cherry-picks (which were done out of order in this case because I missed those changes initially).

**Comment by Kami** [comment]
To confirm all changes are indeed in, one option is to checkout v2.2 locally and diff it to master or v2.2.1_changes (previous branch which was missing those changes).

**Pull request merged**
