### PR TITLE
adding scientific linux support to st2_deploy script. This just adds SL to the list of DISTRO_NAME so the right packages are installed

### PR DESCRIPTION
**Pull request by d-stern**
This just adds scientific linux to the list of DISTRO_NAME so the right packages get installed

### CODE REVIEW

**Comment by DoriftoShoes** [comment]
Almost there :)  I believe lines 533 and 555 need it also.

**Comment by d-stern** [comment]
oops, sorry. Looks like I somehow managed to drop those changes. I'll re-add them now...

**Comment by DoriftoShoes** [comment]
LGTM.  I'll test it out on my end and get it merged.  Thanks!

**Comment by manasdk** [comment]
merge/no-merge?

**Pull request merged**
