### PR TITLE
Move inquiries API path from /exp to /v1

### PR DESCRIPTION
**Pull request by LindsayHill**
It's time to move inquries from `/exp` to `/api/v1`.

API has not changed for months, and we have no short-medium term plans for changing it. 

Time to move it to production path, which also resolves issues such as 
https://github.com/StackStorm/st2/issues/4186

### CODE REVIEW

**Comment by LindsayHill** [comment]
Looks like I didn't get all of the locations, based on those test failures. Will look at it later.

**Comment by LindsayHill** [comment]
Alright, that is much better - all checks passing

**Comment by Kami** [comment]
Do we need to leave it ``/exp`` alias there for a while or you think we are fine?

**Comment by LindsayHill** [comment]
Added Upgrade Notes here https://github.com/StackStorm/st2docs/pull/841

**Comment by ivanmpk** [comment]
Hi, I'm not found /st2client/tests/base.py file, I have the following base.py files:

`/opt/stackstorm/st2/lib/python2.7/site-packages/st2api/controllers/base.py`
`/opt/stackstorm/st2/lib/python2.7/site-packages/st2tests/base.py`

I use ST2 2.10.0

**Comment by LindsayHill** [comment]
@ivanmpk what is it that you're trying to do?

**Comment by ivanmpk** [comment]
Hi I try modify files to inquiry works with environment variable, like this:

https://github.com/StackStorm/st2/pull/4495/files/b0936677d2cb1e625d5ee57dc252a7b41a85eff2

I use ST2 2.9.2 over OpenShift and API URL is not 127.0.0.1 and when execute st2 inquiry list get connection refused to host 127.0.0.1

**Comment by LindsayHill** [comment]
If you're trying to apply this patch manually on your system, why are you looking for a file named st2client/tests/base.py? I don't see any changes to that file in this PR. 

It wouldn't matter anyway - the `tests` content is for unit tests. Are you trying to run those unit tests on your system? Or are you just trying to manually apply the actual code changes to your system?

**Comment by ivanmpk** [comment]
Hi @LindsayHill thanks for your quickly answer, I'm not found this file on my system:

`https://github.com/StackStorm/st2/blob/b0936677d2cb1e625d5ee57dc252a7b41a85eff2/st2api/tests/base.py`

I try apply manually this changes on my system.

**Comment by LindsayHill** [comment]
You don't need those `/tests` directories on a running system. Those are unit tests.

**Pull request merged**
