### PR TITLE
Fix the value of "user" attribute in the context of execution created by alias execution API endpoint

### PR DESCRIPTION
**Pull request by Kami**
This pull request fixes the value of "user" attribute in the "context" of live action created by the alias execution API.

Previously, ``user`` was incorrectly set to system user (``stanley``) instead of the authenticated user which triggered the execution. Not setting the user correctly means RBAC and some other things won't work correctly - token which gets created by the action runner and is available for the duration of the action execution will be tied to the system user (which has no permissions by default) instead of the authenticated user (in workroom case, we create a special use which is used for ChatOps by hubot and we grant that user admin role).

This issue was spotted by @enykeev.

### CODE REVIEW

**Comment by emedvedev** [comment]
LGTM. This issue is a blocker for most default st2 aliases, should we release it as a hotfix or backport it?

**Comment by Kami** [comment]
Yeah, I think it's reasonable to backport it to v1.1.2 :)

**Comment by enykeev** [comment]
Thanks, Kami. I'll wait for the build then make a testing pass and start publishing stuff one by one.

**Comment by Kami** [comment]
Travis failure in master merge is related to mistral auth test - https://github.com/StackStorm/st2/commit/37f4daaf61a8b755ff0ab25c479898c403bf63cb#commitcomment-14442182.

I reverted it for now and will merge this PR.

**Comment by Kami** [comment]
@enykeev I believe packages should be built now. Please let me know how end to end testing goes.

**Pull request merged**
