### PR TITLE
Fix typo: "canel" -> "cancel"

### PR DESCRIPTION
**Pull request by warrenvw**
I can't find reference to "canel" in the code, so hopefully this change won't impact anything negatively.

### CODE REVIEW

**Comment by LindsayHill** [comment]
Don't merge this - I'm almost 100% certain that this is the queue/table name

**Comment by LindsayHill** [comment]
Yup: DO NOT MERGE unless you're going to fix the broken queue name, and figure out how to migrate existing users

```
lhill@st2:~$ sudo rabbitmqctl list_queues | fgrep st2.actionrunner.
st2.actionrunner.canel	0
st2.actionrunner.req	0
st2.actionrunner.work	0
lhill@st2:~$
```

**Comment by armab** [comment]
Update: saw @LindsayHill comment.

Needs a migration or we just leave it as is and call it "easter egg"? :)

**Comment by LindsayHill** [comment]
I saw it a while ago while putting together some monitoring docs. I'd love to get it fixed, but we'll have to figure out a way of doing it that doesn't cause existing users too much pain. It's possible that they'll be OK if they restart ST2 services. Don't really know all the implications.

**Comment by bigmstone** [comment]
I don't believe it needs any special treatment. It should just create the new queue and use it.

Looks like everything consuming it uses it through the return of get_worker so everyone should automagically use the new queue.

**Comment by bigmstone** [comment]
It will leave the `canel` channel hanging around though :D

**Comment by armab** [comment]
On related note, we can rename it to `camel` :)

**Comment by LindsayHill** [comment]
At a minimum, highlight it in upgrade/change notes. Some ppl are monitoring those queues - e.g. @codyaray

**Comment by bigmstone** [comment]
Checked out the branch. It is as I said.

```
ubuntu@st2vagrant:~/st2$ sudo rabbitmqctl list_queues | grep st2
st2.actionrunner.cancel 0
st2.actionrunner.canel  0
st2.actionrunner.req    0
st2.actionrunner.work   0
```

```
ubuntu@st2vagrant:~/st2$ st2 run core.local cmd=date
.
id: 58ae1679c4da5f1893b6a29b
status: succeeded
parameters:
  cmd: date
result:
  failed: false
  return_code: 0
  stderr: ''
  stdout: Wed Feb 22 22:53:46 UTC 2017
  succeeded: true
ubuntu@st2vagrant:~/st2$
```

```
ubuntu@st2vagrant:~/st2$ st2 run core.local cmd="echo Start; sleep 30; echo End;" -a
To get the results, execute:
 st2 execution get 58ae1726c4da5f1893b6a2b0
ubuntu@st2vagrant:~/st2$ st2 execution cancel 58ae1726c4da5f1893b6a2b0
action execution with id 58ae1726c4da5f1893b6a2b0 canceled.
ubuntu@st2vagrant:~/st2$ st2 execution list
+--------------------------+------------------------+--------------+-------------------------+-------------------------------+-------------------------------+
| id                       | action.ref             | context.user | status                  | start_timestamp               | end_timestamp                 |
+--------------------------+------------------------+--------------+-------------------------+-------------------------------+-------------------------------+
| 58ae1679c4da5f1893b6a29b | core.local             | stanley      | succeeded (3s elapsed)  | Wed, 22 Feb 2017 22:54:58 UTC | Wed, 22 Feb 2017 22:55:01 UTC |
| 58ae1726c4da5f1893b6a2b0 | core.local             | stanley      | canceled (11s elapsed)  | Wed, 22 Feb 2017 22:56:38 UTC | Wed, 22 Feb 2017 22:56:49 UTC |
+--------------------------+------------------------+--------------+-------------------------+-------------------------------+-------------------------------+
```

**Comment by warrenvw** [comment]
I'll update the changelog and submit a new commit for review later tonight.

**Comment by codyaray** [comment]
@LindsayHill  thanks for looking out for me. good to know!

**Comment by Kami** [comment]
LGTM.

Perhaps also not a bad idea to document this in upgrade notes.

**Comment by armab** [comment]
@warrenvw Let's resolve conflicts & merge it!
Upcoming `v2.4.0` is best for this change.

**Comment by warrenvw** [comment]
This is an "empty" PR.

**Pull request merged**
