### PR TITLE
Add version string to st2tests to make it installable

### PR DESCRIPTION
**Pull request by StephenWeber**
Prior to this change, this will fail:

    cd st2tests/st2tests
    pip install .

After this change that command successfully installs the `st2tests` package. This will also work for installing via GitHub as in:

    pip install -e git+https://github.com/StackStorm/st2.git@v3.2.0#egg=st2tests&subdirectory=st2tests

The original request in #2574 is to get st2tests onto PyPI, and I'm not sure if this will accomplish that request, but this is a good first step.

### CODE REVIEW

**Comment by StephenWeber** [comment]
I see I need to sign the CLA, please wait while I seek approval to do so.

**Comment by StephenWeber** [comment]
I'm blocked on running tests because of #3934, though I might see if I can get enough installed to just run the st2tests integration tests.

**Comment by armab** [comment]
You can also use Vagrant (https://github.com/stackstorm/st2vagrant) or Docker for StackStorm Development as StackStorm comes with lots of requirements and infra, including DB/MQ/etc.

@StephenWeber BTW, do you think it would be easier for you to sign DCO or CLA, considering your work environment?
We might switch to DCO soon.

**Comment by StephenWeber** [comment]
Thanks for the tip on testing!

> do you think it would be easier for you to sign DCO or CLA, considering your work environment?
> We may switch to DCO soon.

We have an internal process for CLA, I do not believe we have a process for DCO but I can ask.

That said, my request is in with Legal and I expect an answer soon.

**Comment by StephenWeber** [comment]
I heard back from legal, and they did say that a DCO would be easier - they prefer to sign company-level CLAs. I haven't gotten confirmation back that I can sign the individual CLA but I expect that to be approved this week.

In the meantime, I suppose I could also branch off of v3.2 and provide a similar PR for that in case a patch ever is released for that? My deployment is using v3.2 for the time being.

**Comment by StephenWeber** [comment]
Integration test error:

    Python wrapper process script took more than 0.31 seconds to execute (0.3175). This most likely means
    that a direct or in-direct import of a module which takes a long time to load has been added (e.g.
    jsonschema, pecan, kombu, etc).`

I know I'm adding a new project import, and it's not over by much (0.0175 seconds) - unfortunately passing tests do not print out the actual value so I don't know how much import time I'm adding to the system with this change..

**Comment by StephenWeber** [comment]
Integration tests failed to complete in time, closing and reopening ticket to trigger a new build.

**Comment by StephenWeber** [comment]
Now the integration tests are back to failing for `test_process_wrapper_exits_in_reasonable_timeframe`, I'll see about running these locally... but I probably need help...

**Pull request closed without merging**
