### PR TITLE
Import ABC from collections.abc for py 3.10 compatibility

### LINKED ISSUE #5006: Importing ABC directly from collections has been deprecated and will be removed in Python 3.10
## SUMMARY

 Importing ABC directly from collections has been deprecated and will be removed in Python 3.10 . Use collections for Python 2 and collections.abc for Python 3. six also has a fix with six.moves.collections_abc .

### STACKSTORM VERSION

master branch and Python 3.8

```
st2client/st2client/utils/types.py
27:class OrderedSet(collections.MutableSet):

st2common/st2common/util/db.py
32:    elif isinstance(value, collections.Mapping):

st2common/st2common/util/pack.py
126:        if isinstance(attribute, (tuple, list, collections.Iterable)):

st2common/st2common/util/types.py
27:class OrderedSet(collections.MutableSet):

st2common/st2common/util/misc.py
140:        if isinstance(v, collections.Mapping):

```

### PR DESCRIPTION
**Pull request by tirkarthi**
Closes #5006

### CODE REVIEW

**Comment by armab** [comment]
Looks like the CI is not happy as this change breaks the platform functionality and both py27 + py36 CI builds in many ways.

**Comment by tirkarthi** [comment]
This was due to a typo where Mutableset has to be MutableSet (Capital S in Set). I have fixed it now.

**Comment by tirkarthi** [comment]
The lint error doesn't make sense since the module name is moves and not Moves with capital M.

```
Using config file /home/travis/build/StackStorm/st2/lint-configs/python/.pylintrc
************* Module st2client.utils.types
E: 20, 0: No name 'collections_abc' in module 'Moves' (no-name-in-module)
Makefile:289: recipe for target '.pylint' failed
```

**Comment by cognifloyd** [comment]
We just reformatted the code with `black`. So, would you rebase your branch on master (resolve any conflicts & reformat with black)? This should help resolve any linting errors.

Also, code on the `master` branch currently targets python 3.6+. We do not support python2.7 anymore, so that should simplify the changes needed here.

Thanks and Cheers!

**Comment by tirkarthi** [comment]
Thanks, I have rebased and resolved conflicts. I have used collections.abc instead of six.moves.collections_abc since the repo is Python 3.6 + only. The lint stage passes now. This change was implemented in Python 3.10 and will become an error : https://github.com/python/cpython/pull/23754

**Review by cognifloyd — APPROVED** [review]
LGTM
A maintainer will need to approve and merge it.

**Comment by tirkarthi** [comment]
Thanks @cognifloyd

**Comment by armab** [comment]
Thanks, @cognifloyd for the heads up.
@tirkarthi can you please add a Changelog record for this enhancement and so we could merge it?

**Review by armab — APPROVED** [review]
LGTM

Thanks for the contribution, @tirkarthi!

**Comment by tirkarthi** [comment]
Thanks all for the review and merge.

**Pull request merged**
