### PR TITLE
[WIP] Add "pack bootstrap" st2client command for bootstraping a new pack

### PR DESCRIPTION
**Pull request by Kami**
Initially it was a standalone tool (https://github.com/StackStorm/st2bootstrap), but after some discussion, I've decided to move it here.

Usage (non-interactive mode):

```bash
st2 pack bootstrap <pack name>
```

Usage (interactive mode):

```bash
st2 pack bootstrap -i [pack name]
```

TODO:

- [ ] Docs on how to use it

### CODE REVIEW

**Comment by manasdk** [comment]
I want to capture my general disagreement with the placement of this tool -
1. IMO st2 cli is a client which works on top of cli. This sort of establishes its clear focus and boundaries. Primarily this means that st2 cli is essentially and operator client and should not have developer tools. Developer tools fit better in an sdk.
2. A tool which allows bootstrapping of a pack fits closer with tools required to work with st2. We could choose to publish a tool like this to st2contrib or in a top level folder `tools`, `sdk` in st2 repo etc.
3.  Somewhere the question of this tool is about delivery and consumption by an end user/developer. As of now the simplest way to deliver the tool or feature seems to be via the st2client which we independently publish to pypi. However, to me this does not seem like the right organization boundary which should really be around is this the right place to put this tool - IMHO we should not put it here but start looking at building out sdk/development tool kit.

**Comment by Kami** [comment]
Yeah, we have already discussed this on Slack a bit, but to re-iterate the possible options:

1. Leave this command in st2client.
2. Bootstrap a new st2sdk (or whatever we want to call it) tool in a separate repo. To being with, this tool can ship with a single "pack bootstrap" command. We also need to figure out how voodoo and other tools tie into that.
3. Add the tool to st2incubator.
4. Standalone repo for a bootstrap tool. I started with that (https://github.com/StackStorm/st2bootstrap), but, I'm not a big fan of this approach.

I'm leaning towards option 1 or 2. I think option 3 kinda defeats the purpose since now user needs to clone the repo and run the right script which adds additional steps. One of the benefits of option 1 is that st2client will mostly likely already be available on the StackStorm pack author computer so there is less friction to get started with pack development.

/cc @lakshmi-kannan @DoriftoShoes @dzimine et al. - feedback welcome.

Unrelated to this change, in the future, I think we should split st2client into two components and version both of them independently of st2:

1. st2client - Python client for StackStorm API (released as a standalone package on PyPi). Think of it as st2.js but for Python.
2. st2cli - Command line tool for working with StackStorm (depends on st2client, released as a standalone package on PyPi).

This way users who only need the Python client can just install st2client. I know this still leaves some open questions - most notably about backward compatibility and figuring out which version of st2client and st2cli works with which version of StackStrorm.

**Comment by manasdk** [comment]
I like  option 2. st2sdk which for now ships with pack bootstrap. We can roll-in voodoo into this as well.

**Comment by manasdk** [comment]
> Unrelated to this change, in the future, I think we should split st2client into two components and version both of them independently of st2.

I am +1 to split. So long as the separate versioning does not lead to confusion I am fine with a different version also.

**Comment by Kami** [comment]
I'm closing this since the tool will be moved in a separate (st2sdk repo).

**Comment by Kami** [comment]
I've made necessary changes and moved the tool to a new st2sdk repo - https://github.com/StackStorm/st2sdk

Eventually we should also work on moving voodoo and other tools there.

**Pull request closed without merging**
