### PR TITLE
Moving Eugen to Friends

### PR DESCRIPTION
**Pull request by armab**
Hey friends, as mentioned during [October](https://github.com/StackStorm/community/issues/126) meeting, I'm planning to step down as a TSC maintainer after helping shipping the `v3.8.1` release.

While assisting here and there during my free time, I'm not using st2 for quite a while now and need to focus energy in other areas.

When StackStorm was transferred to the LF Governance I’m grateful we could build such a diverse TSC team, cut several 🐳 massive releases, adding new features and fixing lots of bugs, gaining trust as a vendor-neutral community-driven opensource project, thanks to a group of 15 (all time high!) core Maintainers.
Today the project is getting a new inflow of Contributors willing to help and I'm looking forward to see more releases and adoption stories in the future!

Honored to be part of the StackStorm movement, I learned a lot and enjoyed time having fun together with a group of really brilliant engineers building cool #opensource stuff. With the last 3+ yrs helping mostly as an open-source volunteer, I can't believe it was ~7 yrs with the project now. These are some great memories and people I’ve met in the Open Source space. Hope our paths will cross again, who knows, maybe in a new st2 committee? At least, I'll need to get st2 up and running under arm64 then 😃 

Thank you everyone who built, was involved and still involved contributing to and maintaining the project, - your work is invaluable. Keep it up, folks! ❤️

### CODE REVIEW

**Comment by nzlosh** [comment]
It's been great working with you Eugen, good luck in your future endeavours.  You've been a valuable part of the community with all the management, administration, development and help you've given to ensure StackStorm is a successful open source projet.  You'll be missed.  Thank you for all you've given. :wave: :heart:

**Review by nzlosh — APPROVED** [review]

**Review by cognifloyd — APPROVED** [review]

**Review by amanda11 — APPROVED** [review]
Thank you so much for all of your hard work, guidance and support.

**Comment by winem** [comment]
It's been great working with you and having you not only contributing to the code but also doing a whole lot of administration and management tasks as well as an awesome job in the community. Thanks for all of that and just the best!

**Review by winem — APPROVED** [review]

**Comment by Kami** [comment]
Thanks a lot for everything and all the best.

**Pull request merged**
