### PR TITLE
cwd for remote_script should use cwd runner param

### PR DESCRIPTION
**Pull request by lakshmi-kannan**
Noticed this issue in st2build001. To use the new runner in st2build001, we need this patch in 0.13.1.

### CODE REVIEW

**Comment by manasdk** [comment]
+1

Can you CP to 0.13.1?

**Comment by manasdk** [comment]
some tests would be nice.

**Comment by Kami** [comment]
Good catch and what @manasdk said.

Besides that, LGTM.

**Comment by lakshmi-kannan** [comment]
@manasdk @Kami Testing this is hard. We'll end up mocking everything. I could add a test in st2tests.

**Comment by manasdk** [comment]
WFM.

**Pull request merged**
