### PR TITLE
RFR - Add ability to specify branch for st2tests

### PR DESCRIPTION
**Pull request by lakshmi-kannan**
* [ ] - https://github.com/StackStorm/st2cd/pull/75

### CODE REVIEW

**Comment by lakshmi-kannan** [comment]
cc: @manasdk This is the for the CI. I am not sure I got everything. LMK.

**Comment by Kami** [comment]
LGTM

**Comment by manasdk** [comment]
+1

Merge away!

**Comment by manasdk** [comment]
We may need to cherry-pick to v1.1.1

**Pull request merged**
