### PR TITLE
Refactor fix-workflow-db to use singledispatch

### PR DESCRIPTION
**Pull request by blag**
Refactor the `_translate_chars` to use single dispatch with the `functools.singledispatch` decorator on Python 3 or the `singledispatch` package on Python 2.

### CODE REVIEW

**Comment by Kami** [comment]
Just a heads up - as per my research into performance related issues with large documents - this piece of code (translate chars) is quite performance critical and adds substantial overhead on large documents (executions) with many keys so we need to make sure we are not introducing any additional overhead :)

**Comment by m4dcoder** [comment]
This is neat trick.

**Comment by blag** [comment]
I have some rough performance profile results.

# Methodology #

## Housekeeping ##

I only ran the code under Python 3:

```
$ python --version
Python 3.8.1
```

First I made sure that the profile code was testing out every statement and branch of `mongoescape.py`:

```bash
PYTHONPATH=.:st2common coverage run --branch --include=st2common/st2common/util/mongoescape.py --concurrency=eventlet profile_mongoescape.py && coverage annotate && coverage html
```

Then I ran the code with `cProfile`:

```bash
PYTHONPATH=.:st2common python -m cProfile -s cumtime profile_mongoescape.py
```

I profiled both branches with 10000 iterations and 1000000 iterations to try to amortize any overhead, and only looked at the cumulative time spent in `unescape_chars` and `escape_chars`.

I also profiled the code after @m4dcoder's rebase to use the previous explicit `for` loop instead of the list comprehension.

# Results #

## `unescape_chars` - cumulative time ##

(lower values are better)

| `for` loop | 10000x | 1000000x |      | List comp | 10000x | 1000000x |
| ---------- | ------ | -------- | ---- | --------- | ------ | -------- |
| Explicit switches |  1.163 |  121.389 |      |          |  1.326 |  133.674 |
| Single dispatch |  1.587 |  161.334 |      |          |  1.779 |  170.857 |
|            | ------ | -------- |      |          | --------- | ------ | -------- |
| Relative | 36.457% |  32.907% |      |          | 34.163% |  27.816% |

## `escape_chars` - cumulative time ##

(lower values are better)

| `for` loop | 10000x | 1000000x |      | List comp | 10000x | 1000000x |
| ---------- | ------ | -------- | ---- | --------- | ------ | -------- |
| Explicit switches |  0.887 |   91.946 |      |          |  1.000 |   100.790 |
| Single dispatch |  1.229 |  124.071 |      |          |  1.361 |  130.67 |
|            | ------ | -------- |      |          | --------- | ------ | -------- |
| Relative |  38.557% |  34.939% |      |          |  36.1% |  29.646% |

# Conclusion #

Unfortunately, as cool as it is, using `functools.singledispatch` under Python 3 substantially (approximately 33%) slower than simply explicitly coding the field type switches.

Because this code needs to be fast more than it needs to be simple to understand, I'll be closing this PR.

# Code #

## `profile_mongoescape.py` ##

```python
from st2common.util.mongoescape import escape_chars, unescape_chars


for i in range(1000000):
    escape_chars(4)

    escape_chars("four")

    escape_chars("dot.notation")

    escape_chars("dollar$sign")

    escape_chars({
        "untouched": "untouched value",
        "dot.notation": "dot.notation",
        "dollar$sign": "dollar$sign value",
    })

    escape_chars({
        "ne$ted_dict": {
            "untouched": "untouched value",
            "dot.notation": "dot.notation",
            "dollar$sign": "dollar$sign value",
        },
        "nested_dict": {
            "untouched": "untouched value",
            "dot.notation": "dot.notation",
            "dollar$sign": "dollar$sign value",
        },
    })

    escape_chars([{
        "untouched": "untouched value",
        "dot.notation": "dot.notation",
        "dollar$sign": "dollar$sign value",
    }, {
        "untouched2": "untouched2 value",
        "dot.notation2": "dot.notation2 value",
        "dollar$sign2": "dollar$sign2 value",
    }])

    unescape_chars(4)

    unescape_chars("four")

    unescape_chars(u"dot\uFF0Enotation")

    unescape_chars(u"dollar\uFF04sign")

    unescape_chars({
        "untouched": "untouched value",
        u"dot\uFF0Enotation": u"dot\uFF0Enotation value",
        u"dollar\uFF04sign": u"dollar\uFF04sign value",
        "literal dot.notation": "literal dot.notation value",
        "liternal dollar$sign": "literal dollar$sign value",
    })

    unescape_chars({
        "ne$ted_dict": {
            "untouched": "untouched value",
            u"dot\uFF0Enotation": u"dot\uFF0Enotation value",
            u"dollar\uFF04sign": u"dollar\uFF04sign value",
            "literal dot.notation": "literal dot.notation value",
            "liternal dollar$sign": "literal dollar$sign value",
        },
        "nested_dict": {
            "untouched": "untouched value",
            u"dot\uFF0Enotation": u"dot\uFF0Enotation value",
            u"dollar\uFF04sign": u"dollar\uFF04sign value",
            "literal dot.notation": "literal dot.notation value",
            "liternal dollar$sign": "literal dollar$sign value",
        },
    })

    unescape_chars([{
        "untouched": "untouched value",
        u"dot\uFF0Enotation": u"dot\uFF0Enotation value",
        u"dollar\uFF04sign": u"dollar\uFF04sign value",
        "literal dot.notation": "literal dot.notation value",
        "literal dollar$sign": "literal dollar$sign value",
    }, {
        "untouched2": "untouched2 value",
        u"dot.notation2": "dot.notation2 value",
        u"dollar$sign2": "dollar$sign2 value",
    }])
```

**Comment by armab** [comment]
Thanks @blag for digging deeper and @Kami for raising the performance concerns.

**Pull request closed without merging**
