### PR TITLE
Add a custom gunicorn sync worker implementation which works around some issues

### PR DESCRIPTION
**Pull request by Kami**
This includes a custom sync worker implementation which includes a work-around for shutdown related issues when using sync worker in combination with eventlet monkey patching,.

### CODE REVIEW

**Comment by estee-tew** [comment]
https://stackstorm.slack.com/archives/stackstorm/p1457555334007138

**Comment by manasdk** [comment]
@kami - where did you find out that this was the workaround. Did you read gunicorn code to decide which method to overwrite?

**Comment by Kami** [comment]
@manasdk Yep, I checked the sync and base worker implementation.

Without that it fails with the error below inside `handle_quit` (https://github.com/benoitc/gunicorn/blob/master/gunicorn/workers/base.py#L170).

```python
    assert hub.greenlet is not current, 'do not call blocking functions from the mainloop'
AssertionError: do not call blocking functions from the mainloop
```

I'm not too big of a fan of this work-around, but dunno. There are also other issues with async (eventlet) based worker.

**Comment by manasdk** [comment]
@kami If you want to still merge this change please include reference to code from gunicorn in the new file so it is easy for someone to track this down in the future.

**Comment by Kami** [comment]
@manasdk Does af54ffb8571592fec12d4da29db626f45d8a2121 make it any more clear?

**Pull request merged**
