### PR TITLE
[WIP] Fix for #3866 - Adding input information to workflows

### PR DESCRIPTION
**Pull request by nmaludy**
### Intro

This is some initial work on fixing #3866 where `input`s are missing from the execution information for workflows.

### Mistral Input Changes 

Now we properly query Mistral for `input` data off of the `action_execution` for the task. Previously when running `st2 execution get --detail` the `input` parameter for any workflow tasks was always `null`.

```shell
[root@stackstorm ~]# st2 execution get --detail 5a67e8f9a814c0349e2fa1f9
+-----------------+--------------------------------------------------------------+
| Property        | Value                                                        |
+-----------------+--------------------------------------------------------------+
| id              | 5a67e8f9a814c0349e2fa1f9                                     |
| action.ref      | examples.mistral-workbook-subflows                           |
| context.user    | st2admin                                                     |
| parameters      |                                                              |
| status          | succeeded (7s elapsed)                                       |
| start_timestamp | Wed, 24 Jan 2018 02:01:29 UTC                                |
| end_timestamp   | Wed, 24 Jan 2018 02:01:36 UTC                                |
| result          | {                                                            |
|                 |     "tagline": "5a67e8f9a814c0349e2fa1fc is                  |
|                 | 5a67e8fca814c0349e2fa200!",                                  |
|                 |     "tasks": [                                               |
|                 |         {                                                    |
|                 |             "state_info": null,                              |
|                 |             "name": "print_subject",                         |
|                 |             "workflow_name": "examples.mistral-workbook-     |
|                 | subflows.main",                                              |
|                 |             "created_at": "2018-01-24 02:01:29",             |
|                 |             "updated_at": "2018-01-24 02:01:32",             |
|                 |             "workflow_execution_id": "fb1bcd38-5d8c-         |
|                 | 4f98-ba64-0e35ba8db43f",                                     |
|                 |             "state": "SUCCESS",                              |
|                 |             "result": {                                      |
|                 |                 "extra": {                                   |
|                 |                     "state_info": null,                      |
|                 |                     "state": "SUCCESS"                       |
|                 |                 },                                           |
|                 |                 "tasks": [                                   |
|                 |                     {                                        |
|                 |                         "state_info": null,                  |
|                 |                         "name": "task1",                     |
|                 |                         "created_at": "2018-01-24 02:01:30", |
|                 |                         "updated_at": "2018-01-24 02:01:30", |
|                 |                         "id": "2dcea6c0-fff5-4a4d-895b-      |
|                 | 03625824907c",                                               |
|                 |                         "workflow_execution_id": "90379b5d-  |
|                 | 7aef-4324-aa98-d62ae58c9b9f",                                |
|                 |                         "state": "SUCCESS",                  |
|                 |                         "result": {                          |
|                 |                             "succeeded": true,               |
|                 |                             "failed": false,                 |
|                 |                             "return_code": 0,                |
|                 |                             "stderr": "",                    |
|                 |                             "stdout":                        |
|                 | "5a67e8f9a814c0349e2fa1fc"                                   |
|                 |                         },                                   |
|                 |                         "published": {                       |
|                 |                             "stdout":                        |
|                 | "5a67e8f9a814c0349e2fa1fc"                                   |
|                 |                         },                                   |
|                 |                         "input": null,                       |
|                 |                         "workflow_name": "examples.mistral-  |
|                 | basic"                                                       |
|                 |                     }                                        |
|                 |                 ],                                           |
|                 |                 "stdout": "5a67e8f9a814c0349e2fa1fc"         |
```

Now, when you run `st2 execution get --detail` you'll see the inputs

```shell
[root@stackstorm ~]# st2 execution get --detail 5a6923cfa814c00f5a4ae170
+-----------------+--------------------------------------------------------------+
| Property        | Value                                                        |
+-----------------+--------------------------------------------------------------+
| id              | 5a6923cfa814c00f5a4ae170                                     |
| action.ref      | examples.mistral-workbook-subflows                           |
| context.user    | st2admin                                                     |
| parameters      |                                                              |
| status          | succeeded (8s elapsed)                                       |
| start_timestamp | Thu, 25 Jan 2018 00:24:47 UTC                                |
| end_timestamp   | Thu, 25 Jan 2018 00:24:55 UTC                                |
| result          | {                                                            |
|                 |     "tagline": "5a6923d0a814c00f5a4ae173 is                  |
|                 | 5a6923d2a814c00f5a4ae177!",                                  |
|                 |     "tasks": [                                               |
|                 |         {                                                    |
|                 |             "state_info": null,                              |
|                 |             "name": "print_subject",                         |
|                 |             "workflow_name": "examples.mistral-workbook-     |
|                 | subflows.main",                                              |
|                 |             "created_at": "2018-01-25 00:24:47",             |
|                 |             "updated_at": "2018-01-25 00:24:50",             |
|                 |             "workflow_execution_id": "20986eee-c145-4714     |
|                 | -806c-52106272c6ce",                                         |
|                 |             "state": "SUCCESS",                              |
|                 |             "result": {                                      |
|                 |                 "extra": {                                   |
|                 |                     "state_info": null,                      |
|                 |                     "state": "SUCCESS"                       |
|                 |                 },                                           |
|                 |                 "tasks": [                                   |
|                 |                     {                                        |
|                 |                         "state_info": null,                  |
|                 |                         "name": "task1",                     |
|                 |                         "created_at": "2018-01-25 00:24:48", |
|                 |                         "updated_at": "2018-01-25 00:24:48", |
|                 |                         "id": "c811bb5b-494f-4152-82ff-      |
|                 | 3795b06c5b6a",                                               |
|                 |                         "workflow_execution_id": "e2a0495c-  |
|                 | b9dc-433a-bdde-7d59b0fa20a6",                                |
|                 |                         "state": "SUCCESS",                  |
|                 |                         "result": {                          |
|                 |                             "succeeded": true,               |
|                 |                             "failed": false,                 |
|                 |                             "return_code": 0,                |
|                 |                             "stderr": "",                    |
|                 |                             "stdout":                        |
|                 | "5a6923d0a814c00f5a4ae173"                                   |
|                 |                         },                                   |
|                 |                         "published": {                       |
|                 |                             "stdout":                        |
|                 | "5a6923d0a814c00f5a4ae173"                                   |
|                 |                         },                                   |
|                 |                         "action": "core.local",              |
|                 |                         "input": {                           |
|                 |                             "cmd": "echo                     |
|                 | 5a6923d0a814c00f5a4ae173"                                    |
|                 |                         },                                   |
|                 |                         "workflow_name": "examples.mistral-  |
|                 | basic"                                                       |
|                 |                     }                                        |
|                 |                 ],                                           |
|                 |                 "stdout": "5a6923d0a814c00f5a4ae173"         |
````

### st2 run/st2 execution get Changes

Currently the output of `st2 run` and `st2 execution get` print the `result` as the "result" of the final task in the workflow. One of the implications of the changes above is that the `input` data is present in the "result" of the task. This means is that if there is `secret` information in the input then it will be printed out on the CLI. To help mitigate this i've made changes to `st2client` that prints out the published variables of the workflow instead of the "result" of the last task. This seemed more logical to me anyways as it's technically the "result" of the workflow and what's present in the `result` object when interacting with it in Jinja/YAQL.

Example:

```shell
[root@stackstorm ~]# st2 run examples.mistral-basic cmd="echo 'echo hello'"
id: 5a693993a814c00f5a4ae1a4
action.ref: examples.mistral-basic
parameters: 
  cmd: '********'
status: succeeded
result_task: task1
result: 
  stdout: echo hello
start_timestamp: Thu, 25 Jan 2018 01:57:39 UTC
end_timestamp: Thu, 25 Jan 2018 01:57:45 UTC
+--------------------------+------------------------+-------+------------+-----------------+
| id                       | status                 | task  | action     | start_timestamp |
+--------------------------+------------------------+-------+------------+-----------------+
| 5a693994a814c00f5a4ae1a7 | succeeded (1s elapsed) | task1 | core.local | Thu, 25 Jan     |
|                          |                        |       |            | 2018 01:57:40   |
|                          |                        |       |            | UTC             |
+--------------------------+------------------------+-------+------------+-----------------+
```

### TODO

- [ ] Document all of the changes in output
- [ ] Convince self
- [ ] Convince others
- [ ] Figure out better way to mask secrets

### CODE REVIEW

**Comment by Kami** [comment]
Thanks for the contribution.

How does this affect performance? It looks like it results in an additional HTTP request for each task.

Is it possible (and worth) to optimize it to use batch retrieve for all the tasks in a single HTTP call and change the logic to populate tasks inputs at the end and not inside the `_format...` method?

**Comment by m4dcoder** [comment]
@nmaludy We are trying to clear the PR queues. Is this still applicable?  Can you follow up on @Kami questions if so?

**Comment by nmaludy** [comment]
@m4dcoder Yes, still applicable i just haven't had time to finish it up. I need to "get in the zone" on this one again. Hopefully have some time over the next few days to get it finished up.

**Comment by nmaludy** [comment]
Don't care about this anymore as Mistral is going away.

**Pull request closed without merging**
