### PR TITLE
Only checkout if short_branch != branch

### PR DESCRIPTION
**Pull request by lakshmi-kannan**
Fixes: https://github.com/StackStorm/st2/issues/3477

### CODE REVIEW

**Comment by Kami** [comment]
Did you figure this one out?

Was it related to a non-bash shell being used?

**Comment by lakshmi-kannan** [comment]
>Was it related to a non-bash shell being used?

Yeah, it's my zshell. Nevertheless, this fix is a reasonable one IMO.

**Comment by Kami** [comment]
I'm fine with it as long as we test it well.

We had a lot of bugs and edge cases related to this code.

If you verified all the various scenarios (checking out non-default branch, default branch, non-master branch is a default one, etc). and we add a test case for it I'm fine with merging it.

**Comment by Kami** [comment]
Is this still relevant?

**Comment by lakshmi-kannan** [comment]
I'll close this. Will reopen when I have time to actually test this for all cases.

**Pull request closed without merging**
