### PR TITLE
Remove st2common logging dependency from st2client

### PR DESCRIPTION
**Pull request by m4dcoder**

### CODE REVIEW

**Comment by Kami** [comment]
LGTM, +1

(and also sorry, I think I made change)

**Comment by Kami** [comment]
One thing we could eventually do to get rid of copy and paste is copy the file over during build in Makefile, similar as we do with `dist_utils.py`.

**Comment by m4dcoder** [comment]
@Kami: Don't worry about it.

**Comment by m4dcoder** [comment]
That's an interesting idea. Do you mean still reference st2common but copy over on make?  But how will it impact unit testing?

**Pull request merged**
