### PR TITLE
Allow for specifying the branch for packs.install

### PR DESCRIPTION
**Pull request by gtmanfred**
This is nice to have so that we can test our own separately and don't have to only commit to master.

Thanks
Daniel

### CODE REVIEW

**Comment by manasdk** [comment]
+1

Will  merge it in!

**Comment by gtmanfred** [comment]
No problem, thanks for merging it quickly :)

**Comment by manasdk** [comment]
That borked the build, fix is here - 

https://github.com/StackStorm/st2/pull/1129

Will make some build changes so travis picks up. Probably take stab at that early next week.

**Comment by jfryman** [comment]
@gtmanfred :trophy: for the first public code commit! :+1:

**Pull request merged**
