### PR TITLE
Installer docs update

### PR DESCRIPTION
**Pull request by emedvedev**
Docs update to reflect the new “Enterprise” section.

### CODE REVIEW

**Comment by dzimine** [comment]
+1, 
please merge here and to v1 branch, too.

**Comment by manasdk** [comment]
The patch brnach to cherry pick to would be v1.1.1

**Comment by emedvedev** [comment]
Done: https://github.com/StackStorm/st2/commits/v1.1.1

**Comment by dzimine** [comment]
thanks!

**Pull request merged**
