### PR TITLE
Update webhooks.py to enable form POSTs

### PR DESCRIPTION
**Pull request by drpitman**
replaced lines 84-90 with 84-93 - this enables external webhooks to POST the request body as either application/json or regular web-form-style querystring encoded fields. I'm using this on a number of client servers for the last month and it works fine.

### CODE REVIEW

**Comment by Kami** [comment]
First thanks for the contribution!

I believe I suggested something similar in the past - supporting multiple body formats for the webhook body (there might even be a ticket for it :)).

As far as implementation goes - I would prefer the code to be more strict and explicit and select the corresponding body parser based on the request's `Content-Type` header value (`application/json`, `application/x-www-form-urlencoded` /  `multipart/form-data`). This way we could also support XML and similar if needed.

**Comment by drpitman** [comment]
OK, cool. This suited my immediate purposes, but I'll look at a better implementation along your thoughts there in the near future.

**Comment by manasdk** [comment]
Like to PR. Agree with Kami on using headers to explicitly check for supported content-type and unmarshall accordingly.

**Comment by Kami** [comment]
@drpitman Alright, thanks.

I will go ahead and make the content type changes and merge the PR into master :)

**Comment by Kami** [comment]
@drpitman Alright, I made the changes I have mentioned above in #2477.

Thanks again for your PR.

**Pull request merged**
