### PR TITLE
Support single quote in actionaliasexecution

### PR DESCRIPTION
**Pull request by manasdk**
* values with spaces can be represented either by single or double quotes

### CODE REVIEW

**Comment by Kami** [comment]
Do we need to make same changes to hubot plugin?

**Comment by manasdk** [comment]
> Do we need to make same changes to hubot plugin?

Not same but related. Doing that right now.

**Comment by Kami** [comment]
Yeah, that's what I meant :)

To confirm (I didn't see that in tests, maybe I missed it), does this allow user to mix quotes (e.g. one string is quoted using single quotes and one is using double quotes)?

**Comment by manasdk** [comment]
> does this allow user to mix quotes

yes. I am considering that as a +ve thing :)

**Comment by manasdk** [comment]
Corresponding fix in hubot-stackstorm https://github.com/StackStorm/hubot-stackstorm/pull/41

**Pull request merged**
