### PR TITLE
Ignore missing type directories

### PR DESCRIPTION
**Pull request by manasdk**
Fixes regression reported in https://github.com/StackStorm/st2/pull/2291#issuecomment-164944170

### CODE REVIEW

**Comment by lakshmi-kannan** [comment]
lgtm

**Comment by Kami** [comment]
Good catch and thanks :+1: 

It looks like I missed this because we do skip directories which are None in `register_*_from_pack`, but not in `register_*_from_packs`.

**Comment by Kami** [comment]
On a related note - now we have some integration tests for register content script (https://github.com/StackStorm/st2/pull/2291/files#diff-29a7344e3222e95345c48c7d3daba058R1) so it would also be a good idea to add a test case for this scenario.

I will go ahead and do that in a separate PR.

**Comment by Kami** [comment]
Here we go - https://github.com/StackStorm/st2/pull/2300

**Pull request merged**
