### PR TITLE
Add jinja filter to manipulate paths

### PR DESCRIPTION
**Pull request by reisingerf**
I was looking for a jinja filter that could get me the basename or dirname of a linux path string. I have outlined in this pull request how that could look like. Happy for any feedback!

### CODE REVIEW

**Comment by Kami** [comment]
Thanks for the contribution.

The changes look good to me, but you also need to add an entry to a dictionary in `st2common.util.jinja.get_filters` function. That's also the reason why the tests are currently failing.

**Comment by Kami** [comment]
I pushed those changes in https://github.com/StackStorm/st2/pull/4187 (99d0f3d, cc9bc44).

I decided to make those changes myself so we can include those changes in v2.8.0 (deadline for all the changes which will be included in the upcoming v2.8.0 release is today).

Thanks again for your contribution :+1:

**Comment by Kami** [comment]
Just a heads up - I also needed to update the tests - https://github.com/StackStorm/st2/pull/4187/commits/4f6532a6b6253cb9a1922c3257280e8d1bfcc394

**Comment by reisingerf** [comment]
Thanks a lot for your help !
I thought I was missing something, but I wanted to get feedback first before diving deeper into the ST2 code. Thanks for the updates!

FYI: I also submitted a pull request to `st2mistral` ( StackStorm/st2mistral#37 ) as that is my interpretation of the [docs](https://docs.stackstorm.com/reference/jinja.html#custom-jinja-filters), even thought the docs point to a path that does not seem to exist: `st2mistral/st2mistral/filters/`.
I suppose I'm also missing the filter registration on that one...

**Comment by LindsayHill** [comment]
@reisingerf st2docs update to st2mistral path here https://github.com/StackStorm/st2docs/pull/751

**Comment by reisingerf** [comment]
Just fixed related StackStorm/st2mistral#37

**Pull request closed without merging**
