### PR TITLE
Remove get_open_ports action from main product

### PR DESCRIPTION
**Pull request by dzimine**
as it contains a toxic license. TODO: cherrypick to 1.3.

### CODE REVIEW

**Comment by dennybaa** [comment]
looks okay, as for `requirements.txt` you have regenerated em. :+1:

**Comment by manasdk** [comment]
:+1:

**Comment by murgurgula** [comment]
the feature still appears in "st2 action list --pack=linux " which leads to confusion

**Comment by manasdk** [comment]
@murgurgula You can remove with `st2 action delete linux. get_open_ports `.

**Pull request merged**
