### PR TITLE
Pull requirements.txt from specific release

### PR DESCRIPTION
**Pull request by manasdk**
The released version requirements.txt differs from master now therefore the download is also versioned.

### CODE REVIEW

**Comment by Kami** [comment]
LGTM.

IIRC there was some debate about this in the past (I can't recall now why we merged the change to pull requirements.txt from master), but I was always against pulling requirements from master anyway.

**Comment by Kami** [comment]
I found a commit where we made this change - c210a7163b56b4e984e5ad13bd6340c6cf9071d7, but the message doesn't really include the context for it.

/cc @m4dcoder

**Comment by manasdk** [comment]
Yeah will wait on @DoriftoShoes and @m4dcoder to respond.

**Comment by DoriftoShoes** [comment]
I'm not sure why we did this.  I agree that we should be pulling from the downloads server though.

**Comment by Kami** [comment]
We also need to cherry pick this into v0.13.1 branch once it's merged into master.

**Comment by manasdk** [comment]
@m4dcoder Can you look at this PR and https://github.com/StackStorm/st2/commit/c210a7163b56b4e984e5ad13bd6340c6cf9071d7 .

LMK if this is going to be an issue.

**Comment by manasdk** [comment]
I suspect at some point we dropped publishing requirements.txt to the build server; that has since been fixed with https://github.com/StackStorm/st2cd/commit/b0cf6e6e6649ae20bc375f7685f518bfb8e80b79

**Comment by m4dcoder** [comment]
LGTM. I'm not sure why I made the change before. It must have been trying to get around an environment issue.

**Comment by manasdk** [comment]
merging. What could possibly go wrong :P

**Pull request merged**
