### PR TITLE
Add Slack encrypted key for notifications

### PR DESCRIPTION
**Pull request by enykeev**

### CODE REVIEW

**Comment by Kami** [comment]
LGTM, +1

**Comment by lakshmi-kannan** [comment]
@enykeev merge?

**Comment by manasdk** [comment]
Which channel does this get posted to?

**Comment by lakshmi-kannan** [comment]
#30euros.

**Comment by enykeev** [comment]
@lakshmi-kannan I haven't found how to make it only post state changes instead of every success message. If you don't mind, feel free to merge.

@manasdk it was #stackstorm, but you can change it in slack settings

**Comment by lakshmi-kannan** [comment]
Closing this. If we need this back, please reopen.

**Pull request closed without merging**
