### PR TITLE
Allow content pack resources to be disabled via the CLI commands

### PR DESCRIPTION
**Pull request by Kami**
This pull request adds CLI command for disabling and enabling CLI resources (sensors, actions, rules).

Currently it has a known limitation (same as the changes done with via UI) - those changes will be overwritten with the values from disk next time st2-register-content is ran. This will be fixed once the content distribution and syncing is implemented.

### CODE REVIEW

**Comment by lakshmi-kannan** [comment]
I am going to remind you to start splitting this into multiple PRs.

**Comment by Kami** [comment]
@lakshmi-kannan We now have a github pack with `add_comment` action so you can create a StackStorm rule which does this automatically for you :P

**Comment by lakshmi-kannan** [comment]
What's up with this PR @Kami?

**Comment by Kami** [comment]
It's just chillin' along. We need to decide on systematic approach for handling those things.

Most of those attributes get overridden when (re)registering content so exposing those operations doesn't make much sense, but on the other hand, API already exposes those operations so it might be sensible to also have it in the CLI...

**Comment by Kami** [comment]
I brought this PR back from the dead and as discussed, I'll go ahead and merge it into master.

**Pull request merged**
