### PR TITLE
Changed X-XSS-Protection to follow OWASP standards due to deprecation.

### PR DESCRIPTION
**Pull request by LiamRiddell**
Modified the `conf/nginx/st2.conf` to disable the `X-XSS-Protection` functionality in order to align with the OWASP standards. As most browser vendors have deprecated or removed this feature due to the fact it can introduce additional security issues.  Please view the following sources:

OWASP:
image

Mozilla Developer Network Web Docs:
image

References:
OWASP - https://owasp.org/www-project-secure-headers/#x-xss-protection
MDN - https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection

### CODE REVIEW

**Comment by Kami** [comment]
Seems reasonable to me although it would also be good to check the "legacy browsers" list and ensure it's indeed very old version with very little or no usage in real world.

**Comment by LiamRiddell** [comment]
Agreed, I believe we could potentially use `Can I Use?` maintained service to get an idea of browser list. 
https://caniuse.com/mdn-http_headers_x-xss-protection

**Comment by cognifloyd** [comment]
Do we need to replace X-XSS-Protection with CSP? https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP

**Comment by cognifloyd** [comment]
@LiamRiddell Would you please add a changelog entry and replace `X-XSS-Protection` with `Content-Security-Policy`?

**Comment by LiamRiddell** [comment]
@cognifloyd Hi Jacob, apologies. You want me to add a new changelog entry in the "CHANGELOG.rst" file in the root directory of the project? Best, Liam.

**Comment by cognifloyd** [comment]
Correct

**Comment by LiamRiddell** [comment]
> Correct

Do you want me to add it under the "in development" change log?

**Comment by cognifloyd** [comment]
Yes. Then when we cut a release, that section gets renamed to the version number and we add a new in development section.

**Review by cognifloyd — APPROVED** [review]

**Comment by cognifloyd** [comment]
I'm not sure why CircleCI isn't running this PR. I'm going to choose and reopen to trigger it (hopefully)

**Pull request merged**
