### PR TITLE
Fix comments in doc example

### PR DESCRIPTION
**Pull request by vincent-legoll**

### CODE REVIEW

**Comment by Kami** [comment]
Good catch, thanks.

**Comment by vincent-legoll** [comment]
I seem to have another problem with this, the `{{cmdname.stdout}}` thing is throwing me errors, like the following:
```
Failed to run task \"my_task_name\".
Parameter rendering failed: Failed rendering value for action parameter \"text\" in task \"my_task_name\" (template string=Other task output {{my_other_task_name.stdout}}): 'dict object' has no attribute 'stdout'"
```

Whereas the following is working properly: `{{my_other_task_name['192.168.1.157']['stdout']}}`

Am I doing something wrong, or is the doc not accurate ?

Should I open a new issue for that ?

**Comment by Kami** [comment]
Did you try `cmdname.result.stdout`?

**Comment by vincent-legoll** [comment]
I tried a lot of possibilities (and don't remember if I tried this one)...
Trying now, I get:
'dict object' has no attribute 'result'

This is in an ActionChain workflow. ST2 version is:
```
# st2 --version
st2 2.3.1
```

On a "CentOS Linux release 7.3.1611" OpenStack VM

**Comment by Kami** [comment]
Please open a new issue for that so we can continue there and include output of `st2 execution get <execution id> -d`

**Comment by vincent-legoll** [comment]
Created issue  #3649

**Pull request merged**
