### PR TITLE
Fix problems connecting to redis sentinel with SSL

### PR DESCRIPTION
**Pull request by amanda11**
When connecting to redis SSL via sentinel then 2 problems are encountered:

1. redis 3.5.3 did not support ssl parameters for sentinel, see https://github.com/redis/redis-py/pull/1419. So upping the version of redis library
2. When using eventlet and redis SSL then there are connection problems, due to the fact the redis library has expected timeouts, but monkey patched SSL library is throwing different exception. See https://github.com/eventlet/eventlet/issues/692. This causes problems on connecting to redis SSL via sentinel. It also is likely to be the cause of error: https://github.com/StackStorm/st2/issues/5337 as the stack trace encountered is the same.
Therefore when monkey patching SSL library, keep the exception raised on timeout to be socket.timeout.

### CODE REVIEW

**Comment by raviorch** [comment]
Amanda, Please let us know which version of Redis you used to fix the Redis and Sentinel issues for TLS. Redis officially supports TLS from their 6.0 version onwards. Text from redis.io : "SSL/TLS is supported by Redis starting with version 6 as an optional feature that needs to be enabled at compile time." Are you using the latest Redis version 7.0 or 6.2.2?

**Comment by amanda11** [comment]
I used 6.2.7 and compiled at run-time to enable SSL.

**Comment by raviorch** [comment]
Amanda, Thanks for the update, I was wondering if the ssl fix that you have put in also has the fix for providing an username password for Redis. Please let us know.

**Comment by amanda11** [comment]
As far as I know there is no issue with username/password with redis. I've used StackStorm connected to redis secured by username/password before quite happily, on many StackStorm versions including 3.7.0

**Pull request merged**
