### PR TITLE
Remove LindsayHill from TSC

### PR DESCRIPTION
**Pull request by LindsayHill**
I am unable to devote enough time to this project. It would be better for other active contributors to be on the TSC.

### CODE REVIEW

**Comment by armab** [comment]
Thank you Lindsay for all your leadership during the past time as a StackStorm Product Manager and now during the Linux Foundation transition when StackStorm established the new Governance and formed their first Open Source TSC team! :heart: 

@LindsayHill Do you mind if we'll include you in the https://github.com/StackStorm/st2/blob/master/OWNERS.md#friends?
Or maybe if you plan to appear from time to time, in the List of Contributors?

**Comment by LindsayHill** [comment]
Could be added to the "Friends" list, and if I end up spending more time on ST2 in future, I can try for nomination to Contributor

**Comment by armab** [comment]
@LindsayHill Added. Please check the updated description if you'll need to make any adjustments before you merge it.
Thanks buddy for all the impact during these years. It was a honor to be in one team with you!

**Comment by LindsayHill** [comment]
Thanks, looks good

**Pull request merged**
