### PR TITLE
Also start WebUI HTTP server in launchdev

### PR DESCRIPTION
**Pull request by Kami**
Now we also start WebUI HTTP server in launchdev script if the WebUI directory exists.

### CODE REVIEW

**Comment by lakshmi-kannan** [comment]
GoGoGo

**Comment by manasdk** [comment]
This is very strange. I am not sure I agree with starting up components that do not come from this repo. 

We would not want to start up a hubot in launchdev would we?

**Comment by Kami** [comment]
I think it's reasonable to do it with the WebUI since it's a "core" component (unlike hubot which is pluggable and not core).

It was started before when the WebUI was server as part of the API service.

**Comment by enykeev** [comment]
Well, we need to make it clear somehow that webui in the folder is production version. It is read only and is here to make it easier to develop st2. Only for that. For any change in st2web, you need to have a clone of st2web repo and start it with `gulp`.

**Comment by Kami** [comment]
Yeah, launchdev is only meant to be used for development anyway.

I personally handle that via symlinks.

**Comment by manasdk** [comment]
webui is part of API service?

Anyway, I don't like this approach but #yolo. I will not -1 or +1. If you guys want to merge go for it.

**Comment by Kami** [comment]
(it was)

Closing this. @manasdk if you change your mind, let me know :P

**Pull request closed without merging**
