### PR TITLE
Pin networkx to versions lower than 2.6 which doesn't support Python 3.6

### PR DESCRIPTION
**Pull request by nzlosh**
Just seen on CentOS7/8 during package build process:
```
[wheelhouse: st2] [13:58:59]      Processing /tmp/wheelhouse/networkx-2.6.3-py3-none-any.whl
[wheelhouse: st2] [13:58:59]        File was already downloaded /tmp/wheelhouse/networkx-2.6.3-py3-none-any.whl
[wheelhouse: st2] [13:58:59]      ERROR: Package 'networkx' requires a different Python: 3.6.8 not in '>=3.7'
[wheelhouse: st2] [13:58:59]      WARNING: You are using pip version 20.3.3; however, version 21.2.4 is available.
[wheelhouse: st2] [13:58:59]      You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
[wheelhouse: st2] [13:58:59]      make: *** [.stamp-wheelhouse] Error 1
ERROR: 1

Exited with code exit status 1
```
This PR pins networkx to versions lower than 2.6

### CODE REVIEW

**Comment by armab** [comment]
Do we need a Changelog for this?

Per https://app.circleci.com/pipelines/github/StackStorm/st2/2203/workflows/a41eaa05-3034-4f36-aa22-372ca0f83aea/jobs/13713  Ubuntu Bionic build is failing on:
```
[package: st2] [15:15:58]      ERROR: Cannot install -r ./requirements.txt (line 30) and -r ./requirements.txt (line 36) because these package versions have conflicting dependencies.
[package: st2] [15:15:58]      The conflict is caused by:
[package: st2] [15:15:58]          jsonpath-rw 1.4.0 depends on decorator
[package: st2] [15:15:58]          networkx 2.5.1 depends on decorator<5 and >=4.3
```
Or do you think it'll get fixed by the Orquesta https://github.com/StackStorm/orquesta/pull/242 change?

**Comment by winem** [comment]
I can confirm that the Orquesta-PR should fix the failure on U18. 

networkx does no longer require "decorator" as stated in the release notes here: https://github.com/networkx/networkx/blob/v2.6/doc/release/release_2.6.rst

I also checked the code of networkx 2.6 and can confirm that the dependency was dropped (as expected).

**Comment by cognifloyd** [comment]
Here's the issue with decorator:
networkx depends on `decorator<5`, so it should resolve `decorator-4.4.2`. On python3.6, it does just that. On python3.8, however, the wheel does not say that it supports python3.8. That was added 1 commit after the wheel for 4.4.2 was uploaded to pypi. In other words, the commit tagged 4.4.2 on github is one commit past what was used to build the wheel on pypi.
Let's try pinning decorator, a transient dep, to see if that helps pip figure out what to do.

**Comment by cognifloyd** [comment]
Yeah! All CI is passing now

**Review by cognifloyd — APPROVED** [review]

**Comment by cognifloyd** [comment]
Hmm. Maybe we should merge https://github.com/StackStorm/orquesta/pull/242 and update the orquesta commit in this PR as well.

**Review by winem — APPROVED** [review]
Thanks!

**Comment by nzlosh** [comment]
Thanks for the help @cognifloyd and @winem

**Pull request merged**
