### PR TITLE
Allow all basic HTTP methods in core.http

### PR DESCRIPTION
**Pull request by emptywee**
Per https://en.wikipedia.org/wiki/Hypertext_Transfer_Protocol#Request_methods - allow all methods listed, except CONNECT.

### CODE REVIEW

**Comment by emptywee** [comment]
PURGE method is used by nginx api to clear cached content from nginx servers when it's used as a caching load balancer/reverse proxy.

**Comment by Kami** [comment]
Thanks :+1: 

LGTM - can you please add  a changelog entry?

**Comment by emptywee** [comment]
Of course. Though I am not sure under which section it should go: added/changed or fixed? :) I placed it under "changed" for now. Let me know if it's better to move it elsewhere.

**Comment by Kami** [comment]
@emptywee Changed should be fine :)

**Pull request merged**
