### PR TITLE
added virtualenv dependency

### PR DESCRIPTION
**Pull request by dennybaa**
trying to fix virtualenv dependency https://github.com/StackStorm/st2-packages/issues/50

### CODE REVIEW

**Comment by Kami** [comment]
LGTM, but lets also pin it to some known working version / set of versions.

**Comment by dennybaa** [comment]
just a moment... i want to add  st2-auth-backend-flat-file here as well...
I thought recent versions works fine. It'll be > 13.1, @Kami Do you have any specific suggestion?

**Comment by Kami** [comment]
`>=13.1.2,<14.0` just in case :)

**Comment by dennybaa** [comment]
I'm fine to add this version specification. Maybe somebody else wants to draw a word... If not I'll add the above and merge it tomorrow.

**Comment by Kami** [comment]
Just FYI - this change (including virtualenv in top level requirements.txt) might some how breaking workroom.

For now I will remove it from top level requirements.txt (this shouldn't affect your changes), but we should try to dig in and find the root cause,

**Comment by dennybaa** [comment]
Hmm. @Kami I actually haven't added into top level reqs. It shouldn't be there. Where I've added it is `fixed-requirements.txt`. I'd like to add that it's added automatically when you regenerate requirements.

**Comment by Kami** [comment]
@dennybaa I know you haven't added it but we generate top-level `requirements.txt` from those component specific requirements inside our Makefile and include it in the repo.

**Comment by dennybaa** [comment]
@Kami we can easily  remove it from st2client if it's needed. Since there's no use for it until something is decided about refactoring to support STANDALONE components. Split packages can't be used until then anyway.

**Comment by Kami** [comment]
@dennybaa It's fine for now, #2332 solves it :)

But if we decide it it's not needed, then we should remove it, yes.

**Pull request merged**
