### PR TITLE
Integration Tests via Travis

### PR DESCRIPTION
**Pull request by armab**
* [x] Remove code style checks from Travis (in favor of Scrutinizer)
* [x] Configure Integration Tests (create user/etc)
* [x] [Fix `test_encrypt_archive()`, `encrypt_archive()` with gpg integration test issue](https://travis-ci.org/armab/st2/builds/70801345#L809)

### CODE REVIEW

**Comment by armab** [comment]
@manasdk @lakshmi-kannan, this is where I'm in stuck and need your help/ideas:

* log: https://travis-ci.org/StackStorm/st2/jobs/71434949#L1473
* errored test: [st2debug test_encrypt_archive()](https://github.com/StackStorm/st2/pull/1729/files#diff-8a58b2ddb13f4784d6986a001dca17a5R155)
* function: [st2debug encrypt_archive()](https://github.com/StackStorm/st2/blob/travis-integration-tests/st2debug/st2debug/cmd/submit_debug_info.py#L317)

I've included this PR in shared `st2:travis-integration-tests` branch, so you could commit to it/debug.

----
Except of this error, Integration tests in Travis should work OK (verified before in my forked branch).

**Comment by Kami** [comment]
Hm, looking at the changes, we don't run "lint" task anymore? Or am I missing something and we run it as part of a separate job now?

**Comment by Kami** [comment]
Ignore my last comment. I just now saw the "Remove code style checks from Travis (in favor of Scrutinizer)" line in the PR description.

I'm personally not too big of a fan of that. I'd prefer to run everything on Travis CI. This way you only need to go to a single page to see the results.

**Comment by armab** [comment]
There are also some advantages behind that, see: https://github.com/StackStorm/st2/pull/1724

And errored build looks pretty nice: 
https://scrutinizer-ci.com/g/armab/st2/inspections/708d945a-2906-4fe0-9f44-7ef410714e13

Also in usual Travis build if something exited with error - further execution is stopped. See Scrutinizer ^^ log. All tasks are processed, which is especially good for code style checks.

**Comment by armab** [comment]
Last commit provides more fair, aggregate coverage reports.
When code in module A is touched during tests from module B, they are both included in reports now.

Coverage Status  (+4%)

@Kami @lakshmi-kannan @manasdk this PR is ready for review now :eyes:

**Comment by lakshmi-kannan** [comment]
>When code in module A is touched during tests from module B, they are both included in reports now.
That's awesome.

**Comment by manasdk** [comment]
LGTM.

**Comment by lakshmi-kannan** [comment]
LGTM. I'll merge.

**Pull request merged**
