### PR TITLE
Added issue template, update README

### PR DESCRIPTION
**Pull request by LindsayHill**
First draft of an issue template. New issues will be pre-populated with this content.

The goal is to (A) ensure users provide all relevant information, and (B) direct questions towards forum.stackstorm.com

### CODE REVIEW

**Comment by Kami** [comment]
LGTM - maybe we should also mention the new forum somewhere and point people to use that instead of Github issues when it makes sense?

**Comment by LindsayHill** [comment]
We mention the forum on our website & blog. I guess the other places here would be in our README, and the project description? I'll add something to the README fo this PR

**Comment by LindsayHill** [comment]
I've tweaked the project description, and updated README to remove IRC link, add Forum badge & link, and update a few docs URLs to use HTTPS

**Comment by LindsayHill** [comment]
5 updates from master & multiple CI re-runs later, and it's done...

**Pull request merged**
