### PR TITLE
Add HPE to Adopters

### PR DESCRIPTION
**Pull request by andrew-regan**

### CODE REVIEW

**Comment by Kami** [comment]
@andrew-regan Thanks :+1: 

Would you also be interesting in sharing your Plexxi / HPE story and use case with us on our Though Leaders / Case Studies page - https://stackstorm.com/case-studies/ ?

**Comment by andrew-regan** [comment]
I asked our PM team if they want to add some content there. Is the content for that page in the st2 repo as well?

**Comment by Kami** [comment]
@andrew-regan Thanks.

The content is in our Wordpress blog and it's sadly not version controlled in git. You could start a Google Document and share it with us via email (tmuraus or support at extremenetworks dot com).

If you want / if it makes it easier for you, you can also start a Markdown document in a Github gist and share that with us.

**Comment by armab** [comment]
@andrew-regan Awesome to see you guys, one of the oldest StackStorm adopters, in the official list :+1: 
Hope you're doing well in HPE!

**Pull request merged**
