### PR TITLE
Implement proper workflow engine shutdown

### PR DESCRIPTION
**Pull request by khushboobhatia01**
This pull request implements graceful workflow engine shutdown. On shutdown, we stop consuming new requests and give existing active requests some time to complete before we kill the engine.

### CODE REVIEW

**Review by m4dcoder — CHANGES_REQUESTED** [review]
If we are implementing proper shutdown, this is not sufficient.

1. On shutdown, the workflow engine should remove itself from the service registry.
2. If there are other workflow engines in the service registry, then do the shutdown sequence. The shutdown sequence should be something like stop accepting incoming requests and wait until this workflow engine completed processing any requests (not some arbitrary sleep).
3. Else if there are no other workflow engine in the service registry, then the workflow engine needs to stop accepting requests, pause all running workflow executions, and then proceed with rest of the shutdown sequence.
4. On workflow engine startup, any workflow executions paused by the shutdown should be resumed.

**Comment by amanda11** [comment]
@khushboobhatia01 Have we agreed to go for a bigger fix, if so is it ok if i remove this PR from the 3.6 milestone?

**Comment by khushboobhatia01** [comment]
Hi @amanda11, I think we can go ahead and remove the milestone tag. I've started working on the approach we've discussed and will close this MR.

**Comment by amanda11** [comment]
> Hi @amanda11, I think we can go ahead and remove the milestone tag. I've started working on the approach we've discussed and will close this MR.

Thanks for update

**Pull request closed without merging**
