### PR TITLE
[Ignore] Bad PR (scrutinizer check)

### PR DESCRIPTION
**Pull request by armab**
Check that PR fails Scrutinizer build on flake8 (coding style).

### CODE REVIEW

**Comment by lakshmi-kannan** [comment]
Changed decrease threshold to 2%.

**Comment by armab** [comment]
Added another dummy commit.

@lakshmi-kannan removed Coveralls from GitHub commit statuses?

**Comment by armab** [comment]
Works

**Comment by lakshmi-kannan** [comment]
@armab We had coveralls setup under st2stanley as well as my personal github. I unlinked the repo from my personal github.

**Pull request closed without merging**
