### PR TITLE
only apply enabled policies

### PR DESCRIPTION
**Pull request by bri365**
Ensure only enabled policies are applied to actions during scheduling

### CODE REVIEW

**Comment by bri365** [comment]
Duplicates #2811

**Comment by Kami** [comment]
Thanks anyway.

I just recently pushed tests and some other improvements to https://github.com/StackStorm/st2/pull/2811.

I plan to finish and merge it tomorrow and then we will release it in v1.5.2 at some point in the near future (or if you feel adventurous you can try v1.6dev packages from staging :)).

**Comment by bri365** [comment]
@Kami thanks!

**Comment by Kami** [comment]
@bri365 Np.

Will let you know once v1.5.2 with this fix is out (probably some time next week or the week after).

**Pull request closed without merging**
