### PR TITLE
[WIP] ST2_EXP_URL parameter

### PR DESCRIPTION
**Pull request by LindsayHill**
`st2 inquiry list` does not support `ST2_API_URL`. The broader problem is because it uses the `/exp` API, and st2client doesn't handle that.

This WIP code adds support for an `ST2_EXP_URL` parameter. If that's set to say `https://my.st2.com/api/exp`, then you can make remote `st2 inquiry list` calls.

Not sure if this is the right path here or not. Only done minimal testing so far.

Addresses https://github.com/StackStorm/st2/issues/4186

### CODE REVIEW

**Comment by armab** [comment]
Having `EXP_URL` sounds pretty nasty, but it's a good start for discussion.

@Kami Guessing what's the context of `exp`, is it kind of "experimental" API versioning path which was added for Inquiries only?
Considering `/exp/` only adds functionality to `/v1/` and doesn't modify existing endpoints behavior in a breaking change (according to https://api.stackstorm.com/), can we merge `exp` into `v1` maybe?

**Comment by LindsayHill** [comment]
I think there's a few issues/questions here:

1/ No way for users to use st2client to specify server where `/exp` API is hosted. 
2/ Inquiries is still using `/exp` API, but can probably graduate to `/v1`.
3/ Ongoing role of `/exp` vs `/v1`, when one should be used over the other, etc.

I think we need to address all of those. This PR is one way of dealing with the first one.

On the second one, I think we should do some cleanup work on inquiries in 2.9, and move it out of `/exp`. 

For the third one, I think that the reasoning behind using `/exp` here was because the nature of the API might change. Technically it would not break anything moving it to `/v1`, since it is (in this case) additive, but by leaving it behind `/exp`, we are explicitly stating "This API can, and probably will change in the short term". If we move it to `/v1`, users can have an expectation that there will be relatively few changes to that specific API in future, unless we go to `/v2`. So I think there is an ongoing role for an `/exp` API, but things should not stay there forever. We've probably left inquiries there for longer than we should have.

**Comment by nmaludy** [comment]
Maybe a deeper root cause is the fact that things aren't really "based" off of the `base_url`.  Right now, when connecting from an external host, you need to specify several different URLs.

```
    client = st2client.client.Client(base_url="https://{}/".format(server),
                                     auth_url="https://{}/auth/v1".format(server),
                                     api_url="https://{}/api/v1".format(server))
```

Instead, if the code actually used the `base_url` as a base, then the `exp` URL might work as expected?

**Comment by LindsayHill** [comment]
Proper fix here: https://github.com/StackStorm/st2/pull/4495

**Pull request closed without merging**
