### PR TITLE
Some fixes to the st2 action-alias * commands

### PR DESCRIPTION
**Pull request by manasdk**
* `list` -  fixed it and now works
* `get` - added attribute display order

### CODE REVIEW

**Comment by m4dcoder** [comment]
LGTM

**Comment by Kami** [comment]
Both list and get worked fine for me before, wonder what broke it?

In any case, less code, LGTM.

**Comment by manasdk** [comment]
> Both list and get worked fine for me before, wonder what broke it?

List was broken, it would throw an exception at
https://github.com/StackStorm/st2/blob/master/st2client/st2client/models/core.py#L234

Also, get was fine. I added the command to include to reorder the display attributes.

**Comment by manasdk** [comment]
Not sure what changed for list but I did not spend much time investigating either since the fix was simple.

**Comment by Kami** [comment]
Weird. Anyway, good catch and change.

**Pull request merged**
