### PR TITLE
Use -U instead of --password

### PR DESCRIPTION
**Pull request by jamiees2**
This is a somewhat trivial fix extending from #1534

### CODE REVIEW

**Comment by Kami** [comment]
Great, thanks.

I believe tests also need to be updated :)

**Comment by jamiees2** [comment]
Sorry, where are the tests?

**Comment by Kami** [comment]
`st2actions/tests/unit/test_windows_runners.py`

**Comment by jamiees2** [comment]
Yup, found the tests :3 got lost there for a sec.

**Comment by Kami** [comment]
Thanks.

Looks like flake8 step is failing (https://travis-ci.org/StackStorm/st2/jobs/64909343), besides that, it looks good to me.

**Comment by jamiees2** [comment]
Allright, that has been fixed aswell :)

**Comment by Kami** [comment]
Thanks. I've squashed the commits and merged patch intro master.

I've squashed the commits so it will be easier to cherry-pick / backport the change to the 0.9.3 release / branch.

**Comment by Kami** [comment]
Just FYI - this change has been included in 0.11.0 which was released yesterday.

**Pull request closed without merging**
