### PR TITLE
RFR: Move experimental controllers from /exp/ to /v1/

### PR DESCRIPTION
**Pull request by lakshmi-kannan**
See one commit at a time. 

TODO:

* [x] - CHANGELOG (df24791)
* [x] - CLI  (1ce563a)
* [x] - Docs (N/A)
* [x] - Hubot  (https://github.com/StackStorm/hubot-stackstorm/pull/25)

API examples:

```
(virtualenv)/m/s/s/st2 git:exp_controllers_to_v1 ❯❯❯ http POST http://localhost:9101/exp/actionalias/shit                                                                                                                   ⏎ ✭ ✖ ✱ ◼
HTTP/1.1 301 Moved Permanently
Access-Control-Allow-Headers: Content-Type,Authorization,X-Auth-Token
Access-Control-Allow-Methods: GET,POST,PUT,DELETE,OPTIONS
Access-Control-Allow-Origin: http://127.0.0.1:9101/
Access-Control-Expose-Headers: Content-Type,X-Limit,X-Total-Count
Connection: keep-alive
Content-Length: 110
Content-Type: application/json
Date: Tue, 14 Jul 2015 23:41:53 GMT
Location: http://localhost:9101/v1/actionalias/shit

{
    "faultstring": "The resource has been permanently moved to http://localhost:9101/v1/actionalias/shit."
}

(virtualenv)/m/s/s/st2 git:exp_controllers_to_v1 ❯❯❯ http POST http://localhost:9101/exp/aliasexecution/shit                                                                                                                  ✭ ✖ ✱ ◼
HTTP/1.1 301 Moved Permanently
Access-Control-Allow-Headers: Content-Type,Authorization,X-Auth-Token
Access-Control-Allow-Methods: GET,POST,PUT,DELETE,OPTIONS
Access-Control-Allow-Origin: http://127.0.0.1:9101/
Access-Control-Expose-Headers: Content-Type,X-Limit,X-Total-Count
Connection: keep-alive
Content-Length: 113
Content-Type: application/json
Date: Tue, 14 Jul 2015 23:42:01 GMT
Location: http://localhost:9101/v1/aliasexecution/shit

{
    "faultstring": "The resource has been permanently moved to http://localhost:9101/v1/aliasexecution/shit."
}

(virtualenv)/m/s/s/st2 git:exp_controllers_to_v1 ❯❯❯
```

CLI examples:

```
(virtualenv)/m/s/s/s/docs git:exp_controllers_to_v1 ❯❯❯ st2 action-alias list                                                                                                                                                     ✭ ◼
+-------------------+-------+-------------+---------------------------------------------+---------+
| ref               | pack  | name        | description                                 | enabled |
+-------------------+-------+-------------+---------------------------------------------+---------+
| packs.deploy_pack | packs | deploy_pack | Download StackStorm packs via ChatOps       | True    |
| packs.pack_info   | packs | pack_info   | Get StackStorm pack information via ChatOps | True    |
+-------------------+-------+-------------+---------------------------------------------+---------+
(virtualenv)/m/s/s/s/docs git:exp_controllers_to_v1 ❯❯❯
```

### CODE REVIEW

**Comment by lakshmi-kannan** [comment]
@manasdk Feedback appreciated. Not sure if this is what you had in mind.

**Comment by manasdk** [comment]
Works for me.

Do we need client changes? Or does the cli properly handle redirects? Try `st2 action-alias list`

**Comment by lakshmi-kannan** [comment]
We do need client changes for CLI and hubot. If we don't want to do that, redirect(internal=True) will do that. However, from a service perspective we want to send 301. Wdyt? I'll make a note of CLI and hubot changes and work on that.

**Comment by manasdk** [comment]
+1

**Pull request merged**
