### PR TITLE
Remove temp files created by submit_debug_info

### PR DESCRIPTION
**Pull request by vcabbage**
Currently `submit_debug_info.py` doesn't clean up the the temp files it creates. This PR adds a finally statement to remove the temp files created by the `create_archive` function.

Added a remove_dir function to `st2debug/utils/fs.py` for consistency with the `remove_file` function.

### CODE REVIEW

**Comment by Kami** [comment]
Great, thanks.

We also need to make sure directory and file is not removed when using `--review` option, right?

**Comment by vcabbage** [comment]
According to the description, `--review` generates the tarball. This only removes the temp dir, the tarball will still be output.

``` python
    parser.add_argument('--review', action='store_true', default=False,
                        help='Generate the tarball, but don\'t encrypt and upload it')
```

**Comment by Kami** [comment]
@vcabbage Alright, great - then we should be fine.

On a related note - it would be great if you can add a test case for this change.

**Comment by vcabbage** [comment]
Difficult to test as written. I could check the number of files int /tmp and verify there are no additional files after `create_archive` is run, though that sounds a bit flaky. Or I could save the temp dir path to an attribute and check for it's existence directly.

Do you have a preference (or better approach)?

**Comment by Kami** [comment]
Would need to dig in, but in short, we would probably need to modify some methods to store a list of directories and files which are created...

**Comment by vcabbage** [comment]
Since it deletes the entire directory I added a test to check if the directory exists after running. Let me know if that works.

**Comment by Kami** [comment]
Yep, that works - thanks!

**Comment by Kami** [comment]
Merged, thanks.

**Pull request merged**
