### PR TITLE
[WIP] Rescue Python path code

### LINKED ISSUE #5126: Packs that have actions in sub-directories importing modules in same sub-directory fail
## SUMMARY

I have observed in a couple of packs when using StackStorm 3.4dev that they now get ModuleNotFoundError when the pack has a module actions/lib/moduleA.py and that moduleA.py has an import moduleB where moduleB is in the same library.
These packs were working in previous versions.
Observed in both ActiveDirectory and Excel packs.

### STACKSTORM VERSION

st2 3.4dev (c422f0029), on Python 3.6.8

##### OS, environment, install method

CentOS 8.2, single line bash installer

## Steps to reproduce the problem

Observed with following actions:

- activedirectory.get_ad_user
- excel.get_keys_for_rows

## Expected Results

Actions to work as before and not throw ModuleNotFoundError

## Actual Results

Excel Stack Trace:
```
{
  "stdout": "",
  "stderr": "Traceback (most recent call last):
  File \"/opt/stackstorm/st2/lib/python3.6/site-packages/python_runner/python_action_wrapper.py\", line 238, in _get_action_instance
    actions_cls = action_loader.register_plugin(Action, self._file_path)
  File \"/opt/stackstorm/st2/lib/python3.6/site-packages/st2common/util/loader.py\", line 166, in register_plugin
    module = imp.load_source(module_name, plugin_abs_file_path)
  File \"/opt/stackstorm/virtualenvs/excel/lib64/python3.6/imp.py\", line 172, in load_source
    module = _load(spec)
  File \"<frozen importlib._bootstrap>\", line 684, in _load
  File \"<frozen importlib._bootstrap>\", line 665, in _load_unlocked
  File \"<frozen importlib._bootstrap_external>\", line 678, in exec_module
  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed
  File \"/opt/stackstorm/packs/excel/actions/get_keys_for_rows.py\", line 14, in <module>
    from lib import excel_action, excel_reader
  File \"/opt/stackstorm/packs/excel/actions/lib/excel_reader.py\", line 16, in <module>
    import string_converter
ModuleNotFoundError: No module named 'string_converter'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File \"/opt/stackstorm/st2/lib/python3.6/site-packages/python_runner/python_action_wrapper.py\", line 334, in <module>
    obj.run()
  File \"/opt/stackstorm/st2/lib/python3.6/site-packages/python_runner/python_action_wrapper.py\", line 192, in run
    action = self._get_action_instance()
  File \"/opt/stackstorm/st2/lib/python3.6/site-packages/python_runner/python_action_wrapper.py\", line 245, in _get_action_instance
    raise exc_cls(msg)
ModuleNotFoundError: Failed to load action class from file \"/opt/stackstorm/packs/excel/actions/get_keys_for_rows.py\" (action file most likely doesn't exist or contains invalid syntax): No module named 'string_converter'

Traceback (most recent call last):
  File \"/opt/stackstorm/st2/lib/python3.6/site-packages/python_runner/python_action_wrapper.py\", line 238, in _get_action_instance
    actions_cls = action_loader.register_plugin(Action, self._file_path)
  File \"/opt/stackstorm/st2/lib/python3.6/site-packages/st2common/util/loader.py\", line 166, in register_plugin
    module = imp.load_source(module_name, plugin_abs_file_path)
  File \"/opt/stackstorm/virtualenvs/excel/lib64/python3.6/imp.py\", line 172, in load_source
    module = _load(spec)
  File \"<frozen importlib._bootstrap>\", line 684, in _load
  File \"<frozen importlib._bootstrap>\", line 665, in _load_unlocked
  File \"<frozen importlib._bootstrap_external>\", line 678, in exec_module
  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed
  File \"/opt/stackstorm/packs/excel/actions/get_keys_for_rows.py\", line 14, in <module>
    from lib import excel_action, excel_reader
  File \"/opt/stackstorm/packs/excel/actions/lib/excel_reader.py\", line 16, in <module>
    import string_converter
ModuleNotFoundError: No module named 'string_converter'

",
  "exit_code": 1,
  "result": "None"
}
```

Active Directory StackTrace:
```
{
  "stdout": "",
  "stderr": "Traceback (most recent call last):
  File \"/opt/stackstorm/st2/lib/python3.6/site-packages/python_runner/python_action_wrapper.py\", line 238, in _get_action_instance
    actions_cls = action_loader.register_plugin(Action, self._file_path)
  File \"/opt/stackstorm/st2/lib/python3.6/site-packages/st2common/util/loader.py\", line 166, in register_plugin
    module = imp.load_source(module_name, plugin_abs_file_path)
  File \"/opt/stackstorm/virtualenvs/activedirectory/lib64/python3.6/imp.py\", line 172, in load_source
    module = _load(spec)
  File \"<frozen importlib._bootstrap>\", line 684, in _load
  File \"<frozen importlib._bootstrap>\", line 665, in _load_unlocked
  File \"<frozen importlib._bootstrap_external>\", line 678, in exec_module
  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed
  File \"/opt/stackstorm/packs/activedirectory/actions/run_cmdlet.py\", line 1, in <module>
    from lib import action
  File \"/opt/stackstorm/packs/activedirectory/actions/lib/action.py\", line 1, in <module>
    from winrm_connection import WinRmConnection
ModuleNotFoundError: No module named 'winrm_connection'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File \"/opt/stackstorm/st2/lib/python3.6/site-packages/python_runner/python_action_wrapper.py\", line 334, in <module>
    obj.run()
  File \"/opt/stackstorm/st2/lib/python3.6/site-packages/python_runner/python_action_wrapper.py\", line 192, in run
    action = self._get_action_instance()
  File \"/opt/stackstorm/st2/lib/python3.6/site-packages/python_runner/python_action_wrapper.py\", line 245, in _get_action_instance
    raise exc_cls(msg)
ModuleNotFoundError: Failed to load action class from file \"/opt/stackstorm/packs/activedirectory/actions/run_cmdlet.py\" (action file most likely doesn't exist or contains invalid syntax): No module named 'winrm_connection'

Traceback (most recent call last):
  File \"/opt/stackstorm/st2/lib/python3.6/site-packages/python_runner/python_action_wrapper.py\", line 238, in _get_action_instance
    actions_cls = action_loader.register_plugin(Action, self._file_path)
  File \"/opt/stackstorm/st2/lib/python3.6/site-packages/st2common/util/loader.py\", line 166, in register_plugin
    module = imp.load_source(module_name, plugin_abs_file_path)
  File \"/opt/stackstorm/virtualenvs/activedirectory/lib64/python3.6/imp.py\", line 172, in load_source
    module = _load(spec)
  File \"<frozen importlib._bootstrap>\", line 684, in _load
  File \"<frozen importlib._bootstrap>\", line 665, in _load_unlocked
  File \"<frozen importlib._bootstrap_external>\", line 678, in exec_module
  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed
  File \"/opt/stackstorm/packs/activedirectory/actions/run_cmdlet.py\", line 1, in <module>
    from lib import action
  File \"/opt/stackstorm/packs/activedirectory/actions/lib/action.py\", line 1, in <module>
    from winrm_connection import WinRmConnection
ModuleNotFoundError: No module named 'winrm_connection'

",
  "exit_code": 1,
  "result": "None"
}
```

Workarounds were possible to get this to work, e.g. change the ActiveDirectory to use "from .winrm_connection import WinRm"

### PR DESCRIPTION
**Pull request by blag**
This PR partially reverts the code removed in #5100 and refactors it a bit since we no longer need to deal with Python 2.7 at all.

In StackStorm <= v3.3, when the sandboxing code was generating a `PYTHONPATH` for Python actions, it would prepend the operating system's Python directory (eg: `/usr/lib/python3.5`) in an attempt to provide modules and packages from the Python 3 stdlib _before_ the third party packages (usually backports of the same name) for Python 2.7 (eg: `<st2root>/st2/lib/python2.7/site-packages`).

All of that was over-enthusiastically ripped out when we removed Python 2.7 support, however some of the `PYTHONPATH` handling for Python actions is still necessary.

With this PR, the code once again generates an appropriate `PYTHONPATH` for Python actions:

1. The pack's virtualenv `lib` directory (eg: `<st2root>/virtualenvs/<pack>/lib/python3.x`)
2. The pack's virtualenv `site-packages` directory (eg: `<st2root>/virtualenvs/<pack>/lib/python3.x/site-packages`)
3. The pack action `lib` directory (eg: `<st2root>/packs/<pack>/actions/lib`)
4. The Python path (optionally) inherited from the parent process' `PYTHONPATH`, or from the parent virtualenv (the code is only ever [called with both set to `True`](https://github.com/StackStorm/st2/blob/2ae7548b5259394edbb1227d5ca9b56b80908383/contrib/runners/python_runner/python_runner/python_runner.py#L200)), so StackStorm's system `site-packages` directory will always be appended (eg: `<st2root>/st2/lib/python3.x/site-packages`)

As we no longer support Python 2.7, we do not need to prepend the `PYTHONPATH` with the operating system's Python 3 path.

I have also resurrected the tests for this function and refactored them as well.

This might also fix the Windows end-to-end tests that started to fail a few weeks ago.

Related PRs:

* #4297
* #4666
* #4674

Fixes #5126. Special thanks for @amanda11 for catching that before the v3.4 release!

This is currently a WIP. I still need to tweak the tests a bit.

### CODE REVIEW

**Comment by blag** [comment]
I created a `debug` pack with a `pythonpath` action to see what the differences were between ST2 v3.3 and the unfixed v3.4dev. Here were the results:

### StackStorm v3.3 stable on Ubuntu Xenial ###

```
.
id: 6020fde0365119859acc1223
action.ref: debug.pythonpath
context.user: st2admin
parameters: None
status: succeeded
start_timestamp: Mon, 08 Feb 2021 09:01:20 UTC
end_timestamp: Mon, 08 Feb 2021 09:01:20 UTC
result:
  exit_code: 0
  result:
    PYTHONPATH:
    - /usr/lib/python3.5
    - /opt/stackstorm/virtualenvs/debug/lib/python3.5
    - /opt/stackstorm/virtualenvs/debug/lib/python3.5/site-packages
    - /opt/stackstorm/packs/debug/actions/lib/
    - ''
    - /opt/stackstorm/st2/lib/python2.7/site-packages
    sys.path:
    - /opt/stackstorm/virtualenvs/debug/lib/python3/dist-packages
    - /opt/stackstorm/st2/lib/python2.7/site-packages/python_runner
    - /usr/lib/python3.5
    - /opt/stackstorm/virtualenvs/debug/lib/python3.5
    - /opt/stackstorm/virtualenvs/debug/lib/python3.5/site-packages
    - /opt/stackstorm/packs/debug/actions/lib
    - /
    - /opt/stackstorm/st2/lib/python2.7/site-packages
    - /opt/stackstorm/virtualenvs/debug/lib/python35.zip
    - /opt/stackstorm/virtualenvs/debug/lib/python3.5/plat-x86_64-linux-gnu
    - /opt/stackstorm/virtualenvs/debug/lib/python3.5/lib-dynload
    - /opt/stackstorm/packs/debug/actions
  stderr: ''
  stdout: ''
```

### StackStorm v3.3 stable on Ubuntu Bionic ###

```
.
id: 6020e00ebac336e20eddae5a
action.ref: debug.pythonpath
context.user: st2admin
parameters: None
status: succeeded
start_timestamp: Mon, 08 Feb 2021 06:54:06 UTC
end_timestamp: Mon, 08 Feb 2021 06:54:07 UTC
result:
  exit_code: 0
  result:
    PYTHONPATH:
    - /usr/lib/python3.6
    - /opt/stackstorm/virtualenvs/debug/lib/python3.6
    - /opt/stackstorm/virtualenvs/debug/lib/python3.6/site-packages
    - /opt/stackstorm/packs/debug/actions/lib/
    - ''
    - /opt/stackstorm/st2/lib/python3.6/site-packages
    sys.path:
    - /opt/stackstorm/virtualenvs/debug/lib/python3/dist-packages
    - /opt/stackstorm/st2/lib/python3.6/site-packages/python_runner
    - /usr/lib/python3.6
    - /opt/stackstorm/virtualenvs/debug/lib/python3.6
    - /opt/stackstorm/virtualenvs/debug/lib/python3.6/site-packages
    - /opt/stackstorm/packs/debug/actions/lib
    - /
    - /opt/stackstorm/st2/lib/python3.6/site-packages
    - /opt/stackstorm/virtualenvs/debug/lib/python36.zip
    - /opt/stackstorm/virtualenvs/debug/lib/python3.6/lib-dynload
    - /opt/stackstorm/packs/debug/actions
  stderr: ''
  stdout: ''
```

### StackStorm v3.4dev on Ubuntu Bionic (unfixed) ###

```
.
id: 6020f103210e51935211ac3a
action.ref: debug.pythonpath
context.user: st2admin
parameters: None
status: succeeded
start_timestamp: Mon, 08 Feb 2021 08:06:27 UTC
end_timestamp: Mon, 08 Feb 2021 08:06:28 UTC
result:
  exit_code: 0
  result:
    PYTHONPATH:
    - /opt/stackstorm/st2/lib/python3.6/site-packages
    sys.path:
    - /opt/stackstorm/virtualenvs/debug/lib/python3.6/site-packages
    - /opt/stackstorm/st2/lib/python3.6/site-packages/python_runner
    - /opt/stackstorm/st2/lib/python3.6/site-packages
    - /opt/stackstorm/virtualenvs/debug/lib/python36.zip
    - /opt/stackstorm/virtualenvs/debug/lib/python3.6
    - /opt/stackstorm/virtualenvs/debug/lib/python3.6/lib-dynload
    - /usr/lib/python3.6
    - /opt/stackstorm/virtualenvs/debug/lib/python3.6/site-packages
    - /opt/stackstorm/packs/debug/actions
  stderr: ''
  stdout: ''
```

**Comment by Kami** [comment]
I would also hope that with getting rid of Python 2.7 we will be able to simplify that PYTHONPATH logic, but looks like that is sadly not the case :/

**Comment by amanda11** [comment]
I believe there is the intention to encourage everyone to use python3 relative imports but we can't do that when we've not given anyone any warning!
So decided we had to keep that logic in for the moment.

**Review by Kami — APPROVED** [review]
LGTM, although for anything more I would need to dig in (I know that code had various edge cases, for which we did have tests, but yeah removing Python 2.7 support probably exposed some more).

**Comment by Kami** [comment]
@amanda11 Thanks for the additional context.

I do hope that in the future, we will be able to simplify some of that code (although, based on this PR that would mean the change would likely not be fully backward compatible :/)

**Comment by blag** [comment]
Once we force packs to use explicit relative imports instead of implicit relative imports (this is a change made by Python 3 as well), we can simplify some of this a tiny bit.

**Comment by blag** [comment]
Closes #5127 as well.

**Pull request merged**
