### PR TITLE
[CLI] Table improvements

### PR DESCRIPTION
**Pull request by Kami**
Fixes some regressions introduced when adding "elapsed" feature.

### CODE REVIEW

**Comment by manasdk** [comment]
This entire calculation part is horrible. I don't understand the code much anymore.

**Comment by Kami** [comment]
I also cherry picked it into v1.1.1.

**Comment by Kami** [comment]
> This entire calculation part is horrible. I don't understand the code much anymore.

True, it's less than ideal, but I just wanted to get it to work for the common use case. We definitely should clean it up and improve it when we have more time.

**Comment by manasdk** [comment]
Actually I was hoping some library would deal with this mess. But yeah problem for our future us.

**Pull request merged**
