### PR TITLE
Syntax fixes in ActionChain documentation

### PR DESCRIPTION
**Pull request by jfryman**
Minor changes... `parameters` -> `params`.

### CODE REVIEW

**Comment by Kami** [comment]
+1

**Comment by st2stanley** [comment]
Does this need to be cherry-picked anywhere? What's the right way to get this to 0.8.3?

-James 




On Sat, Mar 14, 2015 at 11:56 AM -0700, "Tomaz Muraus" <notifications@github.com> wrote:












+1

**Comment by Kami** [comment]
Could cherry pick it into 0.8.3.

**Comment by jfryman** [comment]
:cherries:-picked to `0.8.3` and merged to master.

**Pull request merged**
