### PR TITLE
Instrument sensor process container code with trigger events

### PR DESCRIPTION
**Pull request by Kami**
This pull request instruments sensor process container code to dispatch an "internal" trigger when a sensor process is started and when it exits.

@jfryman originally mentioned we could dispatch a trigger when a sensor exits when we were discussing how we can making spotting dead sensors easier.

I think instrumenting the whole platform with "internal" triggers (e.g. prefixed with `st2.*`) is a great idea.

For one, we are dog-fooding our platform and we can use this information to perform useful tasks such as self-monitoring and providing useful statistics. At the current stage, we can't really do much with those events yet, but we can at least raise the awareness and help to spot sensor processes which have died (e.g. rule which post message to slack when sensor process exists with a non-zero status code).

Keep in mind that this is just a quick and simple first step to get the discussion going. If we all agree that this is a good idea, we should slowly aim to instrument all the important code paths with the events (e.g. action is started, actions completes - include how long it took, status code, etc.). Instrumenting is first step and after the code is instrumented we can start doing cool things with those events.

And if a queue contention or backlog ever becomes a problem, we can also use a separate queue for internal `st2.*` events.

Feedback is welcome.

### CODE REVIEW

**Comment by Kami** [comment]
Also, to clarify it, this is nothing new. We already emit a trigger when an action has been executed (`st2.generic.actiontrigger`).

This is just making it more "official" and tries to build up a pattern we should follow going forward.

**Comment by manasdk** [comment]
I like the approach. Instrument our system with triggers. Also, you are absolutely right in noticing that we already do this anyway with `st2.generic.actiontrigger` so might as well formalize.

Comments on design -
* Lets get better with the naming and come up with a naming scheme for these triggers. `st2.generic.actiontrigger`, `st2.sensor.process_spawn` and `st2.sensor.process_exit`. Already we have inconsistency in the name (who exactly thought *generic* was a good idea). So naming scheme?
proposal : naming schema `st2.{component}.{trigger_specific_underscored_name}`
* Right now all triggerinstances get published to the same exchange. I think it would be nice to separate internal triggers and true external triggers. We can start by attaching `tags` to internal triggers. Could even post Internal triggers to their MQ exchange. Can have a separate instance of internal `RulesEngine` to process internal triggers also - this idea can get hairy.
* So what do we do with these internal triggers?
** Internal tracking and useful debugging
** Help work out self healing systems (st2 heals itself ... restart failed processes)
** Include in user workflows.

Comments on impl -
* We should register a TriggerType/Trigger for each of these new triggers in a common way. Even ActionTrigger is kinda broken in that sense. (I will push a commit to bring some sanity)

My vote : +2

**Comment by Kami** [comment]
> Comments on design -

Lets get better with the naming and come up with a naming scheme for these triggers. st2.generic.actiontrigger, st2.sensor.process_spawn and st2.sensor.process_exit. Already we have inconsistency in the name (who exactly thought generic was a good idea). So naming scheme? proposal : naming schema st2.{component}.{trigger_specific_underscored_name}

I'm +1 for that and agree on the proposed naming scheme. In fact, that's the naming scheme I followed with the new triggers :)

It seems like we should have some kind of development docs where we can document conventions like this. We could also have a function (e.g. `get_full_ame_for_internal_trigger(component, trigger_name)`, but we need docs anyway.

> Right now all triggerinstances get published to the same exchange. I think it would be nice to separate internal triggers and true external triggers. We can start by attaching tags to internal triggers. Could even post Internal triggers to their MQ exchange. Can have a separate instance of internal RulesEngine to process internal triggers also - this idea can get hairy.

+1 here as well. That's also something I mentioned above, but more as a performance optimization change.

> We should register a TriggerType/Trigger for each of these new triggers in a common way. Even ActionTrigger is kinda broken in that sense. (I will push a commit to bring some sanity)

Yep, I plan to make that change here - for now, I will register it in the same place where we register generic action trigger.

Also, I assume everyone is OK with renaming the action trigger to follow the new scheme? For example: `st2.action.execution_completed` (or similar). And we can also emit more events when the execution has been scheduled, started, etc.

**Comment by Kami** [comment]
I pushed a change to register all internal trigger types inside the action sensor module where actiontrigger registration happened before - 3945afc4da23cea37c5f7100e94ed3f5dff613a5

As debated before, this approach is awful and eventually we should move registration elsewhere (imports shouldn't have side affects).

I will open a separate PR for renaming actiontrigger for consistency purposes.

**Comment by Kami** [comment]
I've decided to clean up the import side affect mess and technical debt and made the registration of internal triggers explicit - now it happens inside the action runner and sensor container (both of those services dispatch and internal trigger).

**Pull request merged**
