### PR TITLE
Execution cli params

### PR DESCRIPTION
**Pull request by manasdk**
* Include parameters for it is annoying to not know what the parameters were; lesson learned while working with the CLI in prod
* yaml >> json

__Before__
* Run a command
```
$ st2 run core.local uname
.
id: 560d8c3932ed357fe4f1d4b5
status: succeeded
result:
{
    "failed": false,
    "stderr": "",
    "return_code": 0,
    "succeeded": true,
    "stdout": "Linux"
}
```

* View previous execution
```
$ st2 execution get 560d82b032ed357f9a189273
id: 560d82b032ed357f9a189273
status: succeeded
result:
{
    "failed": false,
    "stderr": "",
    "return_code": 0,
    "succeeded": true,
    "stdout": "Thu Oct  1 12:00:00 PDT 2015"
}
```
__After__
* Run a command
```
$ st2 run core.local uname
.
id: 560d8bc532ed357fe4f1d4b2
status: succeeded
parameters:
    cmd: uname
result:
    failed: false
    return_code: 0
    stderr: ''
    stdout: Linux
    succeeded: true
```

* View previous execution
```
$ st2 execution get 560d82b032ed357f9a189273
id: 560d82b032ed357f9a189273
status: succeeded
parameters:
    cmd: date
result:
    failed: false
    return_code: 0
    stderr: ''
    stdout: Thu Oct  1 12:00:00 PDT 2015
    succeeded: true
```

### CODE REVIEW

**Comment by DoriftoShoes** [comment]
What about fetching ONLY parameters for an execution?

**Comment by manasdk** [comment]
What about fetching ONLY parameters for an execution?

```
$ st2 execution get 560d8df132ed357fe4f1d4bb --attr parameters
parameters:
    cmd: cat /tmp/CHANGELOG.rst
(virtualenv)manas@st2dev:~/st2$ st2 execution get 560d8df132ed357fe4f1d4bb --attr parameters
parameters:
{
    "cmd": "cat /tmp/CHANGELOG.rst"
}
```

**Comment by manasdk** [comment]
before and after for large outputs - https://gist.github.com/manasdk/619a590d4e9db45aca06

**Comment by Kami** [comment]
LGTM :+1:

**Comment by manasdk** [comment]
Validated st2tests locally.

**Pull request merged**
