### PR TITLE
Docs auto-check broken cross-references.

### PR DESCRIPTION
**Pull request by dzimine**
* This will check for broken cross-references and fail sphinx if one found.

### CODE REVIEW

**Comment by dzimine** [comment]
Looking at what to do with this, hints welcome. 
```
Warning, treated as error:
/home/vagrant/st2/docs/source/actions.rst:435: WARNING: py:class reference target not found: st2actions.runners.pythonrunner.Action
```

**Comment by dzimine** [comment]
@Kami pls take a look at ways to not generate warnings by `autodoc`; what I have there is dirty.

**Comment by Kami** [comment]
I had a look at the linking issue and I believe it's a bug in Sphinx.

If i add `:autoclass:` above `:class:` call it works. This most likely indicates a bug in `:class` directive (for some reason module is not imported if autoclass is not used earlier).

**Comment by Kami** [comment]
Also, good call on enabling nitpicky option :+1:

**Pull request merged**
