### PR TITLE
Remove old packaging

### PR DESCRIPTION
**Pull request by armab**
> Part of @Kami's cleanup [Remove obsolete tools/st2ctl file](https://github.com/StackStorm/st2/commit/90839f68c98766434fdc4b4cb747b36ebf36331a)

After moving packaging to [`st2-packages`](https://github.com/stackstorm/st2-packages), looks this is not used anymore and could be deleted to avoid confusion.

----
@DoriftoShoes's :church: blessing is needed here.

### CODE REVIEW

**Comment by Kami** [comment]
Thanks.

If everything pass we should go and merge this and then see what happens to the build system. We might need to remove some old rules otherwise stuff will fail.

And yeah, @DoriftoShoes probably has a better idea about that.

**Comment by lakshmi-kannan** [comment]
I <3 this. I am glad you took the initiative @armab.

**Comment by manasdk** [comment]
:+1:

**Comment by DoriftoShoes** [comment]
LGTM

**Comment by armab** [comment]
Let's see what happens

**Pull request merged**
