### PR TITLE
The flat_file auth backend reads the Htpasswdfile on every authentica…

### PR DESCRIPTION
**Pull request by manasdk**
…te call.

This enables changes made to htpasswd file dynamic i.e. picked up without
requiring restart of the auth process.

### CODE REVIEW

**Comment by Kami** [comment]
LGTM, +1

Need to also update changelog

**Comment by manasdk** [comment]
> Need to also update changelog

Thinking of cherry-picking to 0.12.2 and making Changelog fixes there and moving the 0.12.2 changelog here eventually.

**Comment by lakshmi-kannan** [comment]
Good catch. Would've been nice to add some tests :P.

**Pull request merged**
