### PR TITLE
Update the requests library version to latest (2.22.0) in requirements

### LINKED ISSUE #4680: Dependency Upgrade: Requests
Requests has fallen behind on dependency upgrades because it needs to be upgraded in multiple places.

### PR DESCRIPTION
**Pull request by VineeshJain**
This PR updates the `requests` package version to the latest (2.22.0) - Closes #4680

### CODE REVIEW

**Comment by m4dcoder** [comment]
@VineeshJain Please fix the commits here.  You should have rebased the first commit, amend the title for the commit, and then push it back into the feature branch. This is such a small change. The additional commits are needless and pollutes the commit history.  Also, please fix the PR title appropriately.  Which module are you updating in requirements?  The PR title doesn't mention which module we are updating.

**Comment by m4dcoder** [comment]
@VineeshJain Can you run `make distclean` and `make requirements` locally and see if additional files are updated.  There are other requirements.txt that gets updated automatically when running `make requirements`.  Those auto updated files need to be included in the PR.

**Comment by VineeshJain** [comment]
I did `make requirements` which gave me 3 additional files other than the `fixed-requirements.txt` file. I committed all 4 of them. Just now I again did `make distclean` and then `make requirements`. No new files came in. This is the output after `make distclean` and `make requirements`

`vagrant@ubuntu-xenial:~/st2$ git status
On branch issue-4680/DependencyUpgradeRequests
Your branch is up-to-date with 'origin/issue-4680/DependencyUpgradeRequests'.
nothing to commit, working directory clean
vagrant@ubuntu-xenial:~/st2$`

**Comment by m4dcoder** [comment]
@VineeshJain Ok thanks for confirming.

**Comment by m4dcoder** [comment]
Please rebase this feature branch with master and then push again. I will approve after.

**Comment by m4dcoder** [comment]
Please also add a CHANGELOG entry.

**Comment by VineeshJain** [comment]
Thanks. Will request @Kami for a review before merging.

**Comment by Kami** [comment]
LGTM.

Let's please just make sure it's tested end to end on all the supported distros (RHEL 6, RHEL 7, Ubuntu 14.04, 16.04 and 18.04).

Please also test it in combination with some packs which explicitly specify version of ``requests`` in ``requirements.txt`` to make sure that there are no conflicts.

**Comment by VineeshJain** [comment]
Yes, I tested end to end explicitly for RHEL6, RHEL7. Commit tested end to end for centos7, Ubuntu 16 and Ubuntu 18. I will run the test explicitly for Ubuntu 14

**Pull request merged**
