### PR TITLE
Update: Add note when "-n" is less than default limit

### PR DESCRIPTION
**Pull request by humblearner**

### CODE REVIEW

**Comment by Kami** [comment]
So far so good, but as mentioned the other day - let's please also add some robotfm tests in addition to unit tests.

**Comment by humblearner** [comment]
Robot tests: https://github.com/StackStorm/st2tests/pull/106 and st2cd action for the tests: https://github.com/StackStorm/st2cd/pull/292

**Comment by Kami** [comment]
Nice work on the tests and thanks for getting rid of the global variable. :+1: 

Well test it a bit later.

**Comment by Kami** [comment]
I've tested it locally and it seems to work fine so I will go ahead and merge it :+1: 

Feel free to merge the tests once new packages are built.

**Pull request merged**
