### PR TITLE
Allow user to specify current working directory when using local and remote runner

### PR DESCRIPTION
**Pull request by Kami**
Current working directory is specified using `cwd` runner parameter.

### CODE REVIEW

**Comment by manasdk** [comment]
LGTM.

Do you want to capture what the default value would be if no CWD is specified?

**Comment by Kami** [comment]
@manasdk Where should I put this? Runner description?

**Comment by manasdk** [comment]
In the description of cwd would be great. I guess once the argument over dir and cwd is resolved.

**Comment by Kami** [comment]
Hm, ugh. I thought I already merged this in master a while ago.

It looks like it missed the boat for 0.7.0 though :(

**Comment by Kami** [comment]
Resolved the merge conflicts and merged it into master - 0.7.1 / 0.8 it is.

**Comment by enykeev** [comment]
Just so you know, the lack of visual difference between "cmd" and "cwd" makes it really hard to distinguish the two in UI. The possible solution might be to either make cmd positional (so it would pop to the top of parameters list) or add a different human-readable name to any of the two.

**Comment by Kami** [comment]
In this case it might make sense to add "friendly names" for the parameters in the UI (e.g. Command, Working directory, etc.).

**Comment by Kami** [comment]
Also, if we ever plan to localize the UI / ship multiple languages, we could just use translation strings for those.

**Pull request merged**
