### PR TITLE
bugfix/ISSUE-5934-fix-rbac-kv-value-render

### PR DESCRIPTION
**Pull request by jschoewe**
Moved permission checks into if statement because we don't need to run checks if no key was found.

This is a fix for the following issue: 
Closes https://github.com/StackStorm/st2/issues/5934

### CODE REVIEW

**Comment by amanda11** [comment]
@jschoewe Please could you sign the CLA, see message above.

**Comment by guzzijones** [comment]
I also just hit this bug.  Knowing that I need to add the key store value helped me resolve it. Thanks.

**Review by guzzijones — APPROVED** [review]
approved. we should not check rbac if no key value is found.

**Review by nzlosh — APPROVED** [review]

**Comment by nzlosh** [comment]
@jschoewe Would you be able to rebase your branch against master so this PR can be merged please?

**Review by armab — APPROVED** [review]

**Comment by armab** [comment]
Tagging this for the upcoming `v3.8.1` patch release.

@jschoewe Could you please update the branch with the latest st2 upstream so we can merge the PR?
I couldn't push to your fork.

**Pull request merged**
