### PR TITLE
Make st2client setup.py requirements consistent

### PR DESCRIPTION
**Pull request by LindsayHill**
Installing st2client using `pip install st2client` has missing dependencies. It is unusable until you run `pip install argcomplete pytz jsonschema prompt_toolkit python-editor`.

This PR makes the setup.py requirements consistent with those in requirements.txt.

Fixes https://github.com/StackStorm/st2/issues/3367

### CODE REVIEW

**Comment by bigmstone** [comment]
@Kami Is the reason you disabled pulling from `requirements.txt` in #2423 still valid or can we re-enable that? It'd be a better fix than trying to manually keep st2client in sync.

**Comment by Kami** [comment]
We fixed `dist_utils.py` so it also works with pip 10.0.0 so I would be OK with reading from `requirements.txt` again if we can indeed verify it works correctly.

**Comment by Kami** [comment]
I did some digging in and testing - we now install pip 9.0.1 inside st2 and pack virtual environments so I believe we should be fine.

It doesn't work with very ancient versions of pip, but I just checked and most other software also doesn't support pip < 9.0 so we should be fine.

I will push a change which updates it to use `requirements.txt` again.

@LindsayHill thanks for opening this PR and having us reevaluate this decision again.

I also tagged this issue with 2.9.0 and will wait with merging this we have a branch for v2.8.

**Comment by Kami** [comment]
I pushed various changes which should resolve that - f9455e235e6304f7951431747f94bcb77824b2ad, 8c6659ccfdfcbb561ba772fd9ae1cab85e0e96df, 79d0d1399f87d8e5588cca0ed587f84673b1e73b.

It should work with pip >= 6.0.0, but we really shouldn't support anything < 9.0.0 so if a user complains, we should ask them to upgrade / use more recent version of pip.

**Comment by LindsayHill** [comment]
Thanks for that @Kami. Totally fine for this to be 2.9.0. It's not a 2.8.0 blocker.

**Comment by Kami** [comment]
I pushed some more changes / fixes to this branch and confirmed it indeed fixes issue reported in #3367 - https://github.com/StackStorm/st2/issues/3367#issuecomment-402174599.

**Pull request merged**
