### PR TITLE
Jinja filters

### PR DESCRIPTION
**Pull request by manasdk**
* jinja filter for regex and working with semver

### CODE REVIEW

**Comment by Kami** [comment]
Nice, I believe that's something I've asked for in the past :)

**Comment by Kami** [comment]
It would also be good to add some docs on custom filters which are available in the templates.

**Comment by Kami** [comment]
To prevent regular expression ddos attacks and pathological use case we should eventually consider using something like re2 - https://pypi.python.org/pypi/re2/

**Comment by manasdk** [comment]
> It would also be good to add some docs on custom filters which are available in the templates.
I got lazy after writing all those tests :package: 

But, I will add docs.

**Comment by manasdk** [comment]
Docs added at 22f19deb2557c118f555612c1f9aa5ecd5451c59. Not the best but atleast filters are enumerated

**Pull request merged**
