### PR TITLE
Propose adding @winem as a Maintainer

### PR DESCRIPTION
**Pull request by armab**
Marcel (@winem) was consistently contributing to the project for the past year and being more actively involved recently, helping delivering the roadmap release items, testing, StackStorm core improvements, community support as well as deployment methods like `curl|bash` scripted installer and Docker.

Some examples:
- `v3.2`, `v3.3` and `v3.4` pre-release testing help, finding bugs and actually helping to resolve them, assisting the team.
- 3.4 roadmap: full `st2resultstracker` removal: https://github.com/StackStorm/st2/pull/5108 https://github.com/StackStorm/st2/issues/5070 https://github.com/StackStorm/st2-packages/pull/683 https://github.com/StackStorm/st2docs/pull/1045 https://github.com/StackStorm/st2-dockerfiles/pull/40 https://github.com/StackStorm/st2-docker/pull/204
- 3.4 roadmap: Assisting in CircleCI to Github Actions migration (https://github.com/StackStorm/st2/pull/5111), participating in the bigger task #5098 for StackStorm/st2
- 3.4: Wider Docker tagging for the container releases: https://github.com/StackStorm/st2-dockerfiles/pull/41 https://github.com/StackStorm/st2-dockerfiles/pull/44
- Documentation Updates here and there: https://github.com/StackStorm/st2/pull/5027 https://github.com/StackStorm/st2docs/pull/1010 https://github.com/StackStorm/st2docs/pull/1016 https://github.com/StackStorm/st2docs/pull/1004  https://github.com/StackStorm/st2docs/pull/1057
- Other minor PRs with enhancements/bugfixes:
  - Assistance in updating `tooz` dependency for st2: https://github.com/StackStorm/st2/pull/5121
  - Add support to force recreation of packs virtualenvs: https://github.com/StackStorm/st2/pull/5167
  - Deadsnakes curl|bash installer fixes: https://github.com/StackStorm/st2-packages/pull/689
- StackStorm v3.5 Roadmap tasks commitments

He's an active team player asking and being able to help where the team needs more assistance and identifying places to fill the gaps. I'd like to propose adding Marcel to the TSC and hope he'll be a good reinforcement to StackStorm Maintainers.

### CODE REVIEW

**Review by amanda11 — APPROVED** [review]

**Review by Kami — APPROVED** [review]

**Review by nmaludy — APPROVED** [review]

**Review by Kami — APPROVED** [review]

**Review by punkrokk — APPROVED** [review]

**Review by punkrokk — APPROVED** [review]

**Review by punkrokk — APPROVED** [review]
Yes!

**Comment by Kami** [comment]
+1, willkommen!

**Review by m4dcoder — APPROVED** [review]

**Review by mickmcgrath13 — APPROVED** [review]

**Comment by armab** [comment]
Thanks, everyone!
Merging per [1 week TSC Voting spec](https://github.com/StackStorm/st2/blob/master/GOVERNANCE.md#how-decisions-are-made).

Welcome @winem to the TSC :+1:  It's a bigger responsibility from now! :)

**Comment by winem** [comment]
Thank you! I'm more than happy to be a maintainer now and will do my best to support the project as well as the community! 

And, since I have a background of more than 10yrs in Linux system & infrastructure engineering, I'm also happy to help if there are any tasks related to internal / infrastructure topics. Just let me know when anything is needed.

**Pull request merged**
