### PR TITLE
Fix `packs/views/file` endpoint throwing error on binary data

### PR DESCRIPTION
**Pull request by enykeev**
Had to fork pecan and manually cherry pick the change from later version.

### CODE REVIEW

**Comment by lakshmi-kannan** [comment]
LGTM. This seems the easiest way to unblock us.

**Comment by Kami** [comment]
Yeah, I'm not the biggest fan of that, but what lakshmi said. Hopefully we can soon get rid of the fork though.

On a related not (minor naming thing) - for consistency with fabric and other forks we should probably name the branch "st2-patched".

**Comment by dzimine** [comment]
Bug in JIRA to track this is needed.

**Comment by enykeev** [comment]
> for consistency with fabric and other forks

```...
git+https://github.com/StackStorm/fabric.git@stanley-patched
...
-e git+https://github.com/Kami/logshipper.git@stackstorm_patched#egg=logshipper
...```

Sure =)

@lakshmi-kannan can we fit it in this release? I'm not merging it because you've asked, but it would be great if you can merge it after you're done with the rest.

**Comment by lakshmi-kannan** [comment]
I don't see a problem with merging it for 0.13.

**Pull request merged**
