### PR TITLE
Integrate "FROM" parameter into send_mail action

### PR DESCRIPTION
**Pull request by pixelrebel**
If a single username is provided, the local hostname is appended.  This allows for default 'stanley' to pass a proper email address. 

Tested in st2 version 0.13.2.5.

### CODE REVIEW

**Comment by Kami** [comment]
Thanks for the PR.

The changes look good to me.

On a related note - if you want you can also tackle footer "issue" in this PR - one option is to also add a footer argument and if not provided, we default to the same old value.

**Comment by pixelrebel** [comment]
>one option is to also add a footer argument and if not provided, we default to the same old value.

This is a bit trickier because the user may want to access the action name and host name in the custom footer.  I was simply suggesting replacing "Stanley" with "StackStorm."  

Then again, I suppose it doesn't hurt to have a custom footer option with no script/host information.  What do you think?

**Comment by Kami** [comment]
I'm fine with replacing Stanley with StackStorm for now :)

**Comment by Kami** [comment]
Thanks, merged into master.

**Pull request merged**
