### PR TITLE
Rule tester updates

### PR DESCRIPTION
**Pull request by manasdk**
- console logging enabled for rule_tester.
- made the start script executable by default.

### CODE REVIEW

**Comment by manasdk** [comment]
@Kami CC.

Merging PR but feel free to comment, I will pick up change.

**Comment by Kami** [comment]
Any particular reason why you have switched to logging? 

It's a standalone short-running script so I don't really see any benefits of using logging. Other components which this script uses do use logging, but those log lines don't really contain anything useful in this case. It just adds clutter and increases verbosity.

**Comment by manasdk** [comment]
> Any particular reason why you have switched to logging?

I was using this for debugging a rule + trigger instance issues that James was seeing. Missing out on logs made it incredibly hard for me to debug the breakage. 

I do agree that logging hurts the simplicity of the script. Would you be more open to a '-v' which then enables logs on the console?

**Comment by Kami** [comment]
> I was using this for debugging a rule + trigger instance issues that James was seeing. Missing out on logs made it incredibly hard for me to debug the breakage.

Ah, OK. I quickly grepped part of the rules engine code which script uses for log calls and I only found one (x rules matched...) which I didn't find useful. It's possible there are other ones which I missed which provide more context and value. If that's the case, then yeah, turning logging on is useful.

> I do agree that logging hurts the simplicity of the script. Would you be more open to a '-v' which then enables logs on the console?

Yeah, having flag for verbosity which turns on the log level would be ideal.

**Comment by manasdk** [comment]
Verbose flag to enable logs e283abb39364723ae6a75177e68ce216ebb79281

**Comment by Kami** [comment]
LGTM, +1

**Comment by jfryman** [comment]
Some quick docs on how to use this would be stellar.

**Comment by Kami** [comment]
There are already docs on how to use rules tester. Unless you means to also document how to use this new flag :)

**Comment by jfryman** [comment]
@Kami derp! Totally missed that! Thanks.... and ignore me. 

http://docs.stackstorm.com/rules.html#testing-rules

**Pull request merged**
