### PR TITLE
Implement with items for Orquesta workflows

### PR DESCRIPTION
**Pull request by m4dcoder**
Add support of with items and concurrency in the task spec of Orquesta workflows. This PR is dependent on changes in the Orquesta engine at https://github.com/StackStorm/orquesta/pull/94. Unit and integration tests are written to cover single and multiple items list, with or without concurrency, and additional operations such as pause, resume, and cancel of workflow while the task is being executed. The following examples are different variations of how workflow authors can define with items for a task.

```
task1:
  with: <% ctx(x) %>
  action: core.echo message=<% item() %>
```

```
task1:
  with:
    items: <% ctx(x) %>
    concurrency: 2
  action: core.echo message=<% item() %>
```

```
task1:
  with: i in <% ctx(x) %>
  action: core.echo message=<% item(i) %>
```

```
task1:
  with:
    items: i in <% ctx(x) %>
    concurrency: 2
  action: core.echo message=<% item(i) %>
```

```
task1:
  with: i, j in <% zip(ctx(x), ctx(y)) %>
  action: mock.foobar a=<% item(i) %> b=<% item(j) %>
```

```
task1:
  with:
    items: i, j in <% zip(ctx(x), ctx(y)) %>
    concurrency: 2
  action: mock.foobar a=<% item(i) %> b=<% item(j) %>
```

### CODE REVIEW

**Comment by m4dcoder** [comment]
@nzlosh This implementation is already operating as you described. The Orquesta conductor will schedule the next item(s) as soon as there are free slots as defined by concurrency.

**Comment by nzlosh** [comment]
:heart: great news! Silly question, is there an option for synchronous `with-items`? :)

**Comment by m4dcoder** [comment]
@nzlosh yep, concurrency=None 😜

**Comment by nzlosh** [comment]
Nice job, that's awesome!! :1st_place_medal: Thanks for the great work!

**Comment by m4dcoder** [comment]
@bigmstone Thanks. I just updated requirements.

**Pull request merged**
