### PR TITLE
 Add inquiry support for orquesta workflows

### PR DESCRIPTION
**Pull request by m4dcoder**
Move inquiry respond related functions to service module. Add inquiry support for orquesta workflows.  Fix a number of related bugs such as removing the pending status from completed states, fix duplicate task execution on subworkflow completion, race condition with resume on inquiry response, and race condition between processing a pending execution and pausing parent.

### CODE REVIEW

**Comment by LindsayHill** [comment]
Looks like this resolves 
https://github.com/StackStorm/st2/issues/4286, 
https://github.com/StackStorm/st2/issues/4135, 
https://github.com/StackStorm/st2/issues/4092

**Comment by m4dcoder** [comment]
@bigmstone this is covered in orquesta-itests

**Comment by shusugmt** [comment]
I've tested this patch by continuously running the test mistral workflow for whole 3 days over 600 times in total and it seems the problem is gone. It never stuck in `pausing` state.

Tested environment:

```
root@10dc28221679:/# dpkg -l|grep st2
ii  st2                             2.9dev-41                                  amd64        StackStorm Event-driven automation
ii  st2chatops                      2.9dev-2                                   amd64        St2Chatops - StackStorm ChatOps.
ii  st2mistral                      2.9dev-5                                   amd64        st2 Mistral workflow service.
ii  st2web                          2.9dev-10                                  amd64        St2Web - StackStorm Web UI.
```

**Comment by shusugmt** [comment]
This also can close #4138 

@LindsayHill #4135 originally addresses a different issue, so I'd like to keep that open. The original issue is to make `st2 inquiry respond` don't do anything (just show an error message and exit) if the root workflow is in `pausing` state. This still can be possible even after this patch is merged and the `pausing` bug is gone.

**Comment by wyjuly** [comment]
Thanks a lot @m4dcoder 
So how can we test this fixing? In the future release 2.8.2 right?

**Comment by wyjuly** [comment]
@m4dcoder  Got it and thanks again.

**Comment by Kami** [comment]
@m4dcoder Nice work on the tests :+1: 

A couple of days ago, I started to notice more intermediate failurrs of mistral inquiry e2e tests. It seems to correlate with the time when this PR was merged. I wonder if it's related.

I would appreciate if you could have a look - here is an example failure https://gist.github.com/Kami/216b3a13abcf7d13d462b12e2cd019b1 (cicd will be rebuilt soon so that execution will be gone and that's why I gist part of it).

**Comment by Kami** [comment]
I believe this should fix the intermediate failure issue - https://github.com/StackStorm/st2tests/commit/504565bac7830c7c97a7fff231a4156ba49b317a

The whole test itself and the way we check for status is quite fragile and not robust, but I just want to get it a bit more reliable without spending the whole day refactoring and improving those tests.

**Comment by m4dcoder** [comment]
@Kami thank you for fixing st2tests! I appreciate your efficiency.

**Pull request merged**
