### PR TITLE
Sensor wrapper global datastore access

### PR DESCRIPTION
**Pull request by Kami**
TODO:

- [x] tests

/cc @jfryman

### CODE REVIEW

**Comment by jfryman** [comment]
`list_value` only? Is it possible to also have a query? I'd like to avoid having responsibility of the sensor to filter.

**Comment by jfryman** [comment]
Also, :metal: and thanks! :heart:

**Comment by Kami** [comment]
@jfryman What kind of filtering do you have in mind?

If you mean just prefix filtering, then, yes, I can add that - I also planned to add this in the future (just wanted to reduce the scope for now) since we already perform this filtering on the client side in the CLI now.

**Comment by jfryman** [comment]
I'd like to be able to do some basic regex searches, or 'contains' searches.

My exact use case: I may have N sets of attributes that are namespaced with `asg.{ASGNAME}.{ASGVALUE}`. So, I'd like to be able to look for maybe all of the keys that are `asg.XXX.alert_status`, and then dig in from there.

I mean, I can easily filter in the sensor itself with some additional code, just feels wrong. :) I don't mind punting, but I fear that this will be a single example might propagate into an anti-pattern very quickly.

**Comment by Kami** [comment]
Alright, in this case, I would really like to avoid users being able to specify regex - this can result in pathological cases, ddos and many other issues.

It sounds like prefix by filter should be a good compromise though - you still need to do late filtering yourself but should be less data :D

**Comment by jfryman** [comment]
> It sounds like prefix by filter should be a good compromise though - you still need to do late filtering yourself but should be less data :D

WFM! :+1:

**Comment by Kami** [comment]
@jfryman Alright, now inside the sensor you can do:

```python
asg_kvps = self._sensor_service.list_values(local=False, prefix='asg.')
```

**Comment by Kami** [comment]
This should also hopefully be helpful now - https://github.com/StackStorm/st2/pull/1122/files#diff-3131793d811778116d7d19aa2e34ee91R62

**Comment by st2stanley** [comment]
Yesssssssss!

-James

**Pull request merged**
