### PR TITLE
Updates for st2 packaging

### PR DESCRIPTION
**Pull request by dennybaa**
A new portion. Consolidating configs into one directory `/etc/st2`.

### CODE REVIEW

**Comment by Kami** [comment]
`st2exporter/conf/logging.conf → st2exporter/conf/logging.exporter.conf`

Do we also need to update `st2exporter.config` to reflect this change?

**Comment by dennybaa** [comment]
Actually it's so https://github.com/StackStorm/st2/blob/master/st2exporter/st2exporter/config.py#L44
it was my previous renaming, but it didn't make sense. So I reverted.

**Comment by Kami** [comment]
LGTM

**Comment by Kami** [comment]
Merged, thanks.

**Pull request merged**
