### PR TITLE
Tidied up help and error messages

### LINKED ISSUE #3135: Outdated instructions when pack requirements not installed
I accidentally tried to run an action without dependencies installed and got the expected error message:

```
  error: '

    Virtual environment (/opt/stackstorm/virtualenvs/napalm) for pack "napalm" doesn''t exist. If you haven''t

    installed a pack using "packs.install" command, you can create a new virtual environment using....
```

In addition to the strange double-quotes for the two contractions in that sentence, we should also update this message to reflect the pack management changes in 2.1

### PR DESCRIPTION
**Pull request by LindsayHill**
Made some minor typo/grammar/language fixes to help strings and error messages

Also fixes #3135

### CODE REVIEW

**Comment by Kami** [comment]
LGTM :+1:

**Comment by Kami** [comment]
I believe this should fix the issue with failing tests - https://github.com/StackStorm/st2tests/pull/124.

**Comment by Kami** [comment]
Confirmed the test change fixed it - will go ahead and merge it.

**Comment by LindsayHill** [comment]
Thanks for sorting out the tests. I had figured that was what needed updating, but hadn't had time to fix it.

**Pull request merged**
