### PR TITLE
1.3.1 fix: Run some st2ctl commands without sudo

### PR DESCRIPTION
**Pull request by dzimine**
Answering https://github.com/StackStorm/st2-packages/issues/134 - that's what I mean.

### CODE REVIEW

**Comment by Kami** [comment]
Which "tasks" don't require sudo / root, just `getpids` or something else as well?

IIRC, it's usually a good idea to use sudo for process listing as well - it used to be a good "hardening" practice to disallows users see processes of other users (I always enabled this on FreeBSD, but IIRC, Linux also supports that).

**Comment by armab** [comment]
Part of https://github.com/StackStorm/st2-packages/issues/134

**Comment by manasdk** [comment]
:+1:

**Comment by manasdk** [comment]
Is it really needed? Its “only” a better error message.

I am all for adding to master btw for next major release but unsure on getting this into v1.3 where we should have changes that are truly necessary for patch.

**Comment by estee-tew** [comment]
https://stackstorm.slack.com/archives/stackstorm/p1454447308004378

**Comment by DoriftoShoes** [comment]
I am +1 to explicitly calling out mistral-api and mistral in st2ctl status.

**Comment by dzimine** [comment]
Ok, I'll keep `mistal-api` from what I see it's no harm to start/stop it explicitly, and benefit of seeing if api is up or down.

**Pull request merged**
