### PR TITLE
Pass limit 0 on in parameters to client

### PR DESCRIPTION
**Pull request by johandahlberg**
I noticed in the CLI that if I ran: `st2 --debug execution list -n 0`, no limit was set in the called url, and only the last 100 executions were returned. According to the documentation if the `-n/--last` parameter is set to 0 all executions should be returned. I believe that this PR should fix this. 

I was also wondering if perhaps settling the limit to less than zero should raise an exception, but now I left the behavior as was.

Have a look and let me know what you think.

### CODE REVIEW

**Comment by Kami** [comment]
Thanks for this contribution.

I would personally prefer to update the docstring and get rid of "list all if 0" part since that behavior is somewhat confusing (zero should mean zero and not all :)). We already have `-l` / `--showall` flag which should serve that purpose.

In any case, I will also wait for others to chime in.

**Comment by johandahlberg** [comment]
@Kami I do agree that it's a bit confusing that 0 means show all. However the `-l / --showall` flag doesn't server exactly the same purpose as it will show the last 50 executions, without collapsing workflow.

`st2 execution list -n 10`:
```
+----------------------------+-------------------------------+--------------+--------------------------+-------------------------------+-------------------------------+
| id                         | action.ref                    | context.user | status                   | start_timestamp               | end_timestamp                 |
+----------------------------+-------------------------------+--------------+--------------------------+-------------------------------+-------------------------------+
|   5783832d48625e7d1bb16c94 | core.remote                   | arteria      | failed (0s elapsed)      | Mon, 11 Jul 2016 11:29:49 UTC | Mon, 11 Jul 2016 11:29:49 UTC |
|   5783834d48625e7d1bb16c96 | core.remote                   | arteria      | succeeded (5s elapsed)   | Mon, 11 Jul 2016 11:30:21 UTC | Mon, 11 Jul 2016 11:30:26 UTC |
|   5783836048625e7d1bb16c98 | core.remote                   | arteria      | succeeded (5s elapsed)   | Mon, 11 Jul 2016 11:30:40 UTC | Mon, 11 Jul 2016 11:30:45 UTC |
|   578383f348625e7d1bb16c9a | core.remote                   | arteria      | succeeded (5s elapsed)   | Mon, 11 Jul 2016 11:33:07 UTC | Mon, 11 Jul 2016 11:33:12 UTC |
|   5783856c48625e7d1bb16c9c | core.remote                   | arteria      | failed (207s elapsed)    | Mon, 11 Jul 2016 11:39:24 UTC | Mon, 11 Jul 2016 11:42:51 UTC |
| + 5783862e48625e7d1bb16c9e | arteria-packs.ngi_uu_workflow | arteria      | succeeded (336s elapsed) | Mon, 11 Jul 2016 11:42:38 UTC | Mon, 11 Jul 2016 11:48:14 UTC |
| + 57838ecd48625e7d1bb16caa | arteria-packs.ngi_uu_workflow | arteria      | succeeded                | Mon, 11 Jul 2016 12:19:25 UTC | Mon, 11 Jul 2016 13:09:54 UTC |
|                            |                               |              | (3029s elapsed)          |                               |                               |
| + 5783941748625e7d1bb16cae | arteria-packs.ngi_uu_workflow | arteria      | succeeded (90s elapsed)  | Mon, 11 Jul 2016 12:41:59 UTC | Mon, 11 Jul 2016 12:43:29 UTC |
| + 57839ab948625e59caf65c68 | arteria-packs.fill_projman    | arteria      | succeeded (538s elapsed) | Mon, 11 Jul 2016 13:10:17 UTC | Mon, 11 Jul 2016 13:19:15 UTC |
| + 5783b6d948625e59caf65e79 | arteria-packs.fill_projman    | arteria      | running (377s elapsed)   | Mon, 11 Jul 2016 15:10:17 UTC |                               |
+----------------------------+-------------------------------+--------------+--------------------------+-------------------------------+-------------------------------+
```

vs. `st2 execution list -n 10 --showall`:
```
+--------------------------+-------------+--------------+-----------------------+-------------------------------+---------------+
| id                       | action.ref  | context.user | status                | start_timestamp               | end_timestamp |
+--------------------------+-------------+--------------+-----------------------+-------------------------------+---------------+
| 5783b86948625e7d1bb174cb | core.remote | arteria      | running (27s elapsed) | Mon, 11 Jul 2016 15:16:41 UTC |               |
| 5783b86748625e7d1bb174c6 | core.remote | arteria      | running (27s elapsed) | Mon, 11 Jul 2016 15:16:41 UTC |               |
| 5783b86648625e7d1bb174c3 | core.remote | arteria      | running (26s elapsed) | Mon, 11 Jul 2016 15:16:42 UTC |               |
| 5783b86548625e7d1bb174c2 | core.remote | arteria      | running (26s elapsed) | Mon, 11 Jul 2016 15:16:42 UTC |               |
| 5783b86b48625e7d1bb174ce | core.remote | arteria      | running (26s elapsed) | Mon, 11 Jul 2016 15:16:42 UTC |               |
| 5783b86548625e7d1bb174c0 | core.remote | arteria      | running (25s elapsed) | Mon, 11 Jul 2016 15:16:43 UTC |               |
| 5783b86d48625e7d1bb174d0 | core.remote | arteria      | running (25s elapsed) | Mon, 11 Jul 2016 15:16:43 UTC |               |
| 5783b86948625e7d1bb174cc | core.remote | arteria      | running (25s elapsed) | Mon, 11 Jul 2016 15:16:43 UTC |               |
| 5783b86848625e7d1bb174c8 | core.remote | arteria      | running (25s elapsed) | Mon, 11 Jul 2016 15:16:43 UTC |               |
| 5783b86d48625e7d1bb174cf | core.remote | arteria      | running (24s elapsed) | Mon, 11 Jul 2016 15:16:44 UTC |               |
+--------------------------+-------------+--------------+-----------------------+-------------------------------+---------------+
```

Since we have some workflows with a lot of tasks in them (500+), we really do need to collapse the workflow to be able to make any sense of the output.

**Comment by Kami** [comment]
Ah, I see what you mean.

I wonder if we should add another flag / option `--expand` / `--dont-expand` or similar, but we already have `--show-tasks` flag so need to make sure everything is consistent and we don't have confusing and contradicting flags and behavior :)

**Comment by Kami** [comment]
Now that I think about it some more - I believe that using default maximum limit / page size when selecting "show all" was done intentionally - to avoid resource exhaustion and DDoS attacks.

I'm fine with allowing users to request all items, as long as that option is opt-in in config (e.g. adding another setting `max_page_size = 100000` or similar).

For safety reasons I think we should still limit max page size to same reasonable default (e.g. 100 items per page), but if users like you have a need for a bigger max page size, they can override it and opt-in in the config :)

@johandahlberg Would you be OK with the behavior described above?

**Comment by lakshmi-kannan** [comment]
>For safety reasons I think we should still limit max page size to same reasonable default (e.g. 100 items per page), but if users like you have a need for a bigger max page size, they can override it and opt-in in the config :)

Last I looked this was the intended behavior from our side. The code is a bit of mess and it's not the first time someone has gotten confused by the ``0`` part. I personally want to get rid of that docstring. So I agree with kami's proposal and I am -1 to the changes in PR although the quality is great with tests :). I am a little bummed to be negative.

**Comment by johandahlberg** [comment]
Absolutely sounds like part of this could be solved by removing the "list all if 0." from the docstring to not confuse things. However, I'm still not sure that I follow this completely.

If I make a request to the API with limit set to it appears that I get back all the workflows since we upgraded to 1.4 (and started from a clean db):

```
curl -X GET -H  'Connection: keep-alive' -H  'User-Agent: python-requests/2.9.1' -H  'Accept-Encoding: gzip, deflate' -H  'Accept: */*' -H  'X-Auth-Token: <the auth token>' 'http://127.0.0.1:9101/v1/executions/?exclude_attributes=result%2Ctrigger_instance&parent=null&limit=0'
```

If I understand things correctly that means that there is a cap on how many items are returned, i.e. setting the `limit` in the request to 500 will still only give me 100 items, but if I set it to 0, I get them all back. So if this is a security issue, I guess that needs to be addressed on the server side?

I'll close this PR, and post an issue about the inconsistency in the docstring. And @lakshmi-kannan don't worry about it, you guys obviously know this code and the decisions taken around it way better that I do. I mostly made this into a PR rather than a issue, or posting about it on the slack channel because it seemed a rather trivial fix, and I thought it would be nicer to just do something about it. :smile:

**Pull request closed without merging**
