### PR TITLE
Perform API input data validation using API model definitions

### PR DESCRIPTION
**Pull request by Kami**
This is a stop gap for regression described in #3575 until we implement a long term solution described in that issue (making sure each openapi entity definition contains corresponding JSON schema which is generated and copied over from API model schema attribute).

It should fix the regression (we didn't perform any API validation for endpoints which didn't have entity json schema defined in openapi.yaml).

The code basically does what we did before move to API v2, but we still need to be careful it doesn't break something.

While working on that, I thought we should actually still call `model.validate()` inside the router when performing API input data validation, even when we automatically generate and move all JSON schema definitions to openapi.yaml.

The reason for that is that `model.validate()` doesn't just validate values, but it also returns a cleaned object with default values assigned (we rely on this functionality in some places). That way, definition in `openapi.yaml` would only be used for documentation and auto-generation purposes.

### CODE REVIEW

**Comment by Kami** [comment]
In theory, it should be fine to include this in v2.3.2 since it's not a new feature but a bug fix for a regression, but we should still keep an eye on tests, etc.

**Comment by enykeev** [comment]
> The reason for that is that model.validate() doesn't just validate values, but it also returns a cleaned object with default values assigned (we rely on this functionality in some places).

We need to identify this places and mark them for refactoring/ If we expect a default value, it should be a part of schema. I suspect there might be some nastier things, though.

**Comment by Kami** [comment]
@enykeev Yes, default values are already part of schema, but the problem is how JSON schema validation works.

It doesn't assign default values (just doesn't fail if default: attribute is there and no value is provided) on validation. For default value assignment to work, we needed to implement our own code.

**Comment by vincent-legoll** [comment]
Just fyi, this breaks something that was previously working fine. I gave as packs.install.packs parameter, a single string representing repo URL.

Now I get a cryptic error saying invalid character at line 1 column 1...

I managed to find what the problem was, and now I have to give ["$URL"] instead...

**Pull request merged**
