### PR TITLE
add policy related statuses

### PR DESCRIPTION
**Pull request by marceloapps**
This pull request is related to the issue https://github.com/StackStorm/st2/issues/4648.
The idea is to add cancel/delay statuses related to when policies afect an action execution.

Changes were made on the constants list, concurrency and concurrency_by_attrib, scheduler handler and tests.

### CODE REVIEW

**Comment by marceloapps** [comment]
Hi guys, do I have to change something here? Didn't quite catch the problem with CI

**Comment by armab** [comment]
Just updated your branch with the latest `master`. Let's see if that fixes CI issues.

For the review, I'd expect @m4dcoder to take a look at it, keeping in mind it's more of his area.

**Comment by m4dcoder** [comment]
The status changes here is going to break a lot of places in st2. The functioning of scheduler and workflow engine are coupled to statuses. I can't tell you specifically where to fix because there are a lot of places where this value change is going to impact.  You'll have to keep iterating until the unit and integrate tests go green.  The other option is to search for all the occurrences of DELAYED and CANCELED status in the code and figure out whether this change impacts it or not and make appropriate changes.  Good luck.

**Review by m4dcoder — CHANGES_REQUESTED** [review]
As commented above, this change is going to cascade and impact a lot of different places in the scheduler, action runner, and workflow engine. This PR is not close to ready.

**Comment by marceloapps** [comment]
Ok, thanks for the review! I'll get to work then, and get back to you guys.

**Comment by Kami** [comment]
I would have swear we had ``policy-delayed`` status in the past which got removed at some point due to some bug which I can't recall anymore.

EDIT: From changelog:

> * Remove policy-delayed status to avoid bouncing between delayed statuses. (bug fix) #4655

Some more context for removal is in that PR. If we want to add it back, we need to ensure that issue is fixed (aka no flipping between states - will likely require changes to the scheduler).

/cc @m4dcoder

**Comment by cognifloyd** [comment]
We just reformatted the code with `black`. (Hooray!) And this PR got caught in the cross fire. (Arrgh!)
So, you'll want to merge master into your branch, resolve the conflicts (sorry!), and reformat your code with black (I recommend using `pre-commit install` so it just happens whenever you commit).

**Comment by cognifloyd** [comment]
What if we added a `reason` field (or something like that) so that whatever cancels or delays an action can document why. That way, you don't have to edit any of the status-based state machines in workflow engine and other places.

**Comment by cognifloyd** [comment]
@marceloapps do you want to pursue this any further? Is it helpful to leave this open?

**Comment by marceloapps** [comment]
We may close this issue for now

**Pull request closed without merging**
